general:
  apolloPlayground: true
  apolloIntrospection: true
  bcryptHashCostFactor: 12
  urlAdapter: default
mailProvider:
  id: mailchimp # allowed is mailchimp/mailgun
  type: mailchimp
paymentProviders:
  - type: payrexx # Allowed are stripe-checkout / stripe / payrexx / bexio
    id: payrexx # Required for stripe-checkout / stripe / payrexx /bexio
  - type: stripe
    id: stripe
  - type: stripe-checkout
    id: stripe-checkout
  - type: mollie
    id: mollie
  - type: payrexx-subscription
    id: payrexx-subscription
  - type: bexio
    id: bexio
  - type: no-charge
    id: no-charge
challenge:
  type: turnstile
  id: 'turnstile'
trackingPixelProviders:
  - type: prolitteris
    id: prolitteris
mediaServer:
  type: 'nova'
  quality: 1
ga:
  credentials:
  property:
  articlePrefix: /a/
v0:
  type: VO
  id: v0
