general:
  apolloPlayground: true
  apolloIntrospection: true
  bcryptHashCostFactor: 12
  urlAdapter: default
mailProvider:
  id: slackMail
  fromAddress: dev@wepublish.ch
  webhookURL: 'SLACK_DEV_MAIL_WEBHOOK_URL'
OAuthProviders:
  - name: 'google'
    discoverUrl: 'https://accounts.google.com'
    clientId: '617896178757-i6ldn0nni9qtle8o6eu76lv93d78nvfi.apps.googleusercontent.com'
    clientKey: 't267ZLqkV9dacrkPQp_pF-G2'
    redirectUri:
      - ${WEBSITE_URL}/auth/google
    scopes:
      - 'openid profile email'

paymentProviders:
  - type: payrexx
    id: payrexx
    name: Payrexx
    offSessionPayments: true
    instanceName: wepublish-sandbox
    instanceAPISecret: xxx
    webhookApiKey: xxx
    psp: [ 0, 15, 17, 2, 3, 36 ]
    pm: ['visa', 'mastercard']
    vatRate: 8.1

  - type: stripe
    id: stripe
    name: Stripe
    offSessionPayments: true
    secretKey: key
    webhookEndpointSecret: wh_secret

  - type: stripe-checkout
    id: stripe-checkout
    name: Stripe Checkout
    offSessionPayments: false
    secretKey: key
    webhookEndpointSecret: wh_secret

  - type: payrexx-subscription
    id: payrexx-subscription
    name: Payrexx Subscription
    instanceName: wepublish-sandbox
    instanceAPISecret: xxx
    webhookEndpointSecret: xxx

  - type: bexio
    id: bexio
    name: Bexio
    apiKey: secret
    userId: '1'
    countryId: '1'
    invoiceTemplateNewMembership: 'template-name'
    invoiceTemplateRenewalMembership: 'template-name'
    unitId: '1'
    taxId: '17'
    accountId: '139'
    invoiceTitleNewMembership: "New Invoice"
    invoiceTitleRenewalMembership: "New Invoice"
    invoiceMailSubjectNewMembership: "Invoice for :memberPlan.name:"
    invoiceMailBodyNewMembership: "Hello :user.firstname:\n\nThank you for subscribing to :memberPlan.name:.\nYou can view your invoice here: [Network Link]\n\nBest wishes from the Wepublish team"
    invoiceMailSubjectRenewalMembership: "Invoice for :memberPlan.name:"
    invoiceMailBodyRenewalMembership: "Hello :user.firstname:\n\nThank you for subscribing to :memberPlan.name:.\nYou can view your invoice here: [Network Link]\n\nBest wishes from the Wepublish team"
    markInvoiceAsOpen: False

challenge:
  secret: 'secret'
  validTime: 600
  width: 200
  height: 200
  background: '#ffffff'
  noise: 5
  minValue: 1
  maxValue: 10
  operandAmount: 1
  operandTypes: [ '+', '-' ]
  mode: 'formula'
  targetSymbol: '?'

mediaServer:
  type: 'nova'