import baseConfig from '../../eslint.config.mjs';
import nx from '@nx/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import eslintPluginSimpleImportSort from 'eslint-plugin-simple-import-sort';
import globals from 'globals';

const config = [
  ...baseConfig,
  ...nx.configs['flat/react-typescript'],
  ...nextCoreWebVitals,
  {
    rules: {
      // React Compiler powered checks newly enabled by the react-hooks preset
      // bundled with eslint-config-next 16; not enforced before the upgrade.
      'react-hooks/refs': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  { plugins: { 'simple-import-sort': eslintPluginSimpleImportSort } },
  { languageOptions: { globals: { ...globals.jest } } },
  {
    rules: {
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@next/next/no-html-link-for-pages': ['error', 'apps/neuewege/pages'],
      'simple-import-sort/imports': 1,
      'simple-import-sort/exports': 1,
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    // Override or add rules here
    rules: {},
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    // The TS rules above also run on the JS sources (src/components, src/lib);
    // some of them (e.g. no-useless-constructor) crash on espree's AST.
    languageOptions: {
      parser: tsParser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {},
  },
  {
    // the ported live DOM (src/components) renders plain <img> elements
    files: ['**/src/components/**/*.js'],
    rules: { '@next/next/no-img-element': 'off' },
  },
  {
    // next-env.d.ts is generated by Next.js and imports build artifacts from dist.
    ignores: ['**/.next/**', '**/next-env.d.ts'],
  },
];

export default config;
