import baseConfig from '../../eslint.config.mjs';
import nx from '@nx/eslint-plugin';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import eslintPluginSimpleImportSort from 'eslint-plugin-simple-import-sort';
import globals from 'globals';

export default [
  ...baseConfig,
  ...nx.configs['flat/react-typescript'],
  ...nextCoreWebVitals,
  {
    rules: {
      // React Compiler powered checks newly enabled by the react-hooks preset
      // bundled with eslint-config-next 16; not enforced before the upgrade.
      'react-hooks/refs': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  { plugins: { 'simple-import-sort': eslintPluginSimpleImportSort } },
  { languageOptions: { globals: { ...globals.jest } } },
  {
    rules: {
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@next/next/no-html-link-for-pages': ['error', 'apps/gruppetto/pages'],
      'simple-import-sort/imports': 1,
      'simple-import-sort/exports': 1,
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    // Override or add rules here
    rules: {},
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    // Override or add rules here
    rules: {},
  },
  {
    // next-env.d.ts is generated by Next.js and imports build artifacts from dist.
    ignores: ['**/.next/**', '**/next-env.d.ts'],
  },
];
