phrase:
  access_token: ece2ea975fa3c95647bf3bbeaadf929837aefec7c90f1ec86e4430404b6261d8
  project_id: f686ad4e7ae0c4960dc1d5ae7a56a6cb
  push:
    sources:
    - file: ./apps/editor/src/app/locales/<locale_name>.json
      params:
        file_format: i18next
  pull:
    targets:
    - file: ./apps/editor/src/app/locales/<locale_name>.json
      params:
        file_format: i18next
