projects:
  editor-api:
    schema:
      - 'apps/api-example/schema-v2.graphql'
    documents: 'libs/editor/api/**/*.graphql'
  website-api:
    schema:
      - 'apps/api-example/schema-v2.graphql'
    documents:
      - 'libs/website/api/**/*.graphql'
  testing:
    schema:
      - 'apps/api-example/schema-v2.graphql'
    documents:
      - 'libs/testing/src/graphql/public/**/*.graphql'
