export enum ReflektBlockType {
  FlexBlockHero = 'FlexBlockHero',
  FlexBlockFullsizeImage = 'FlexBlockFullsizeImage',
  TeaserRecherchen = 'TeaserRecherchen',
  TeaserMoreAbout = 'TeaserMoreAbout',
  TeaserCredits = 'TeaserCredits',
  TeaserNews = 'TeaserNews',
  CollapsibleContent = 'CollapsibleContent',
  CollapsibleDownloads = 'CollapsibleDownloads',
  TableOfContents = 'TableOfContents',
  TextWithImage = 'TextWithImage',
  TextWithImageAltColor = 'TextWithImageAltColor',
  ImageWithText = 'ImageWithText',
  ImageWithTextAltColor = 'ImageWithTextAltColor',
  Team = 'Team',
}
