// THIS FILE IS AUTOGENERATED, EDIT WITH CAUTION

      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {
    "BaseBlock": [
      "BildwurfAdBlock",
      "BlockTemplateBlock",
      "BreakBlock",
      "CommentBlock",
      "CrowdfundingBlock",
      "EventBlock",
      "FacebookPostBlock",
      "FacebookVideoBlock",
      "FlexBlock",
      "HTMLBlock",
      "IFrameBlock",
      "ImageBlock",
      "ImageGalleryBlock",
      "InstagramPostBlock",
      "ListicleBlock",
      "MailchimpFormBlock",
      "PolisConversationBlock",
      "PollBlock",
      "QuoteBlock",
      "RichTextBlock",
      "SoundCloudTrackBlock",
      "StreamableVideoBlock",
      "SubscribeBlock",
      "TeaserGridBlock",
      "TeaserGridFlexBlock",
      "TeaserListBlock",
      "TeaserSlotsAutofillConfig",
      "TeaserSlotsBlock",
      "TikTokVideoBlock",
      "TitleBlock",
      "TwitterTweetBlock",
      "VimeoVideoBlock",
      "YouTubeVideoBlock"
    ],
    "BaseCrowdfundingGoal": [
      "CrowdfundingGoal",
      "CrowdfundingGoalWithProgress"
    ],
    "BaseNavigationLink": [
      "ArticleNavigationLink",
      "ExternalNavigationLink",
      "PageNavigationLink"
    ],
    "BaseTeaser": [
      "ArticleTeaser",
      "CustomTeaser",
      "EventTeaser",
      "PageTeaser"
    ],
    "BaseToken": [
      "Token",
      "TokenWithSecret"
    ],
    "BaseUser": [
      "SensitiveDataUser",
      "User"
    ],
    "BlockContent": [
      "BildwurfAdBlock",
      "BlockTemplateBlock",
      "BreakBlock",
      "CommentBlock",
      "CrowdfundingBlock",
      "EventBlock",
      "FacebookPostBlock",
      "FacebookVideoBlock",
      "FlexBlock",
      "HTMLBlock",
      "IFrameBlock",
      "ImageBlock",
      "ImageGalleryBlock",
      "InstagramPostBlock",
      "ListicleBlock",
      "MailchimpFormBlock",
      "PolisConversationBlock",
      "PollBlock",
      "QuoteBlock",
      "RichTextBlock",
      "SoundCloudTrackBlock",
      "StreamableVideoBlock",
      "SubscribeBlock",
      "TeaserGridBlock",
      "TeaserGridFlexBlock",
      "TeaserListBlock",
      "TeaserSlotsBlock",
      "TikTokVideoBlock",
      "TitleBlock",
      "TwitterTweetBlock",
      "UnknownBlock",
      "VimeoVideoBlock",
      "YouTubeVideoBlock"
    ],
    "HasArticle": [
      "ArticleNavigationLink"
    ],
    "HasBlockContent": [
      "ArticleRevision",
      "BlockTemplate",
      "PageRevision"
    ],
    "HasImage": [
      "ArticleTeaser",
      "Author",
      "BreakBlock",
      "CustomTeaser",
      "EventTeaser",
      "Goodie",
      "ImageBlock",
      "ImageGalleryImage",
      "ListicleItem",
      "MailchimpFormInterestOption",
      "MemberPlan",
      "PageTeaser",
      "QuoteBlock"
    ],
    "HasImageLc": [
      "PaymentMethod"
    ],
    "HasMemberPlan": [
      "PublicSubscription"
    ],
    "HasMemberPlanLc": [
      "DiscountCode"
    ],
    "HasOneBlockContent": [
      "BlockWithAlignment"
    ],
    "HasOptionalArticle": [
      "ArticleTeaser"
    ],
    "HasOptionalCrowdfunding": [
      "CrowdfundingBlock"
    ],
    "HasOptionalEvent": [
      "EventTeaser"
    ],
    "HasOptionalPage": [
      "PageTeaser"
    ],
    "HasOptionalPaywall": [
      "Article"
    ],
    "HasOptionalPeerLc": [
      "Article",
      "Author",
      "Image",
      "PeerArticle"
    ],
    "HasOptionalPoll": [
      "PollBlock"
    ],
    "HasOptionalSubscription": [
      "Invoice"
    ],
    "HasOptionalUser": [
      "Comment"
    ],
    "HasOptionalUserLc": [
      "ArticleRevision",
      "PageRevision"
    ],
    "HasPage": [
      "PageNavigationLink"
    ],
    "HasPaymentMethod": [
      "Payment",
      "PublicSubscription"
    ],
    "HasUser": [
      "PublicSubscription"
    ],
    "SettingProvider": [
      "SettingAIProvider",
      "SettingAnalyticsProvider",
      "SettingChallengeProvider",
      "SettingLetterProvider",
      "SettingMailProvider",
      "SettingPaymentProvider",
      "SettingPdfRenderer",
      "SettingSyncProvider",
      "SettingTrackingPixelProvider"
    ],
    "SubscribeBlockLayoutConfig": [
      "SubscribeBlockLayoutNoneConfig",
      "SubscribeBlockLayoutPickerConfig",
      "SubscribeBlockLayoutSliderConfig"
    ],
    "Teaser": [
      "ArticleTeaser",
      "CustomTeaser",
      "EventTeaser",
      "PageTeaser"
    ]
  }
};
      export default result;
    