version: '3'
services:
  oauth:
    image: oryd/hydra:latest
    ports:
      - "4010:4444"
      - "4011:4445"
    command:
      serve all --dangerous-force-http
    environment:
      URLS_SELF_ISSUER: "http://localhost:4010"
      URLS_SELF_PUBLIC: "http://localhost:4010"
      URLS_LOGIN: "http://localhost:4000/auth/login"
      URLS_CONSENT: "http://localhost:4000/auth/consent"
      URLS_LOGOUT: "http://localhost:4000/auth/logout"
      URLS_ERROR: "http://localhost:4000/auth/error"
      DSN: "postgres://wepublish:1234@db:5432/oauth?sslmode=disable"
      SECRETS_SYSTEM: "youReallyNeedToChangeThis"
      SERVER_ADMIN_CORS_ALLOWED_ORIGINS: '*'
      WEBFINGER_OIDC_DISCOVERY_USERINFO_URL: "http://localhost:4000/auth/userinfo"
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "oauth"
      POSTGRES_USER: "wepublish"
    volumes:
      - ./.postgres-volume:/var/lib/postgresql/data
