import { Test, TestingModule } from '@nestjs/testing';
import {
  SlotTeasersLoader,
  BlockType,
  BaseBlock,
  TeaserType,
  BlockWithAlignment,
  FlexBlock,
  TeaserSlotType,
  isFlexBlock,
  isTeaserSlotsBlock,
  Teaser,
  BlockTemplateBlock,
  BlockTemplateDataloaderService,
} from '@wepublish/block-content/api';
import { EventService } from '@wepublish/event/api';
import { ArticleService } from './article.service';
import { ArticleTeaser, TeaserSlotsBlock } from '@wepublish/website/api';
import nanoid from 'nanoid';

/*
 *
 *
 *
 *  TESTS FOR SLOT TEASERS LOADER
 *  lib/block-content/api/src/lib/teaser/slot-teasers-loader.ts
 *
 *  block-content-api project had to be ingored in ./nxignore because of
 *  circular dependency issues therefore these tests are located in article-api project.
 *
 *
 */

// make sure ids generated by nanoid are predictable for testing purposes
jest.mock('nanoid', () => {
  let counter = -1;
  return () => {
    counter++;
    return `mock_nanoid_${counter}`;
  };
});

const mockFlexBlock = ({
  blockStyle = undefined,
  blocks = [] as BlockWithAlignment[],
} = {}) =>
  ({
    type: BlockType.FlexBlock,
    blockStyle,
    blocks,
  }) as unknown as FlexBlock;

const mockTeaserSlotsBlock = () => {
  return {
    autofillConfig: {
      __typename: 'TeaserSlotsBlockAutofillConfig',
      tagIds: [],
      enabled: true,
      numberOfTeasers: 8,
      sort: null,
      teaserType: 'article' as TeaserType.Article, // explicit lowercase string to match enum value
      filter: {
        __typename: 'TeaserListBlockFilter',
        tags: ['test-tag-id'],
        tagObjects: [
          {
            __typename: 'Tag',
            id: nanoid(),
            tag: `lorem-ipsum`,
          },
        ],
      },
    },
    slots: [
      {
        type: TeaserSlotType.Autofill,
      },
      {
        type: TeaserSlotType.Autofill,
      },
      {
        type: TeaserSlotType.Autofill,
      },
      {
        type: TeaserSlotType.Autofill,
      },
      {
        type: TeaserSlotType.Autofill,
      },
      {
        type: TeaserSlotType.Autofill,
      },
      {
        type: TeaserSlotType.Autofill,
      },
      {
        type: TeaserSlotType.Autofill,
      },
    ],
    type: BlockType.TeaserSlots,
  } as unknown as BaseBlock<BlockType>;
};

const mockTeaserSlotsBlockWithManualTeaser = () => {
  return {
    autofillConfig: {
      __typename: 'TeaserSlotsBlockAutofillConfig',
      tagIds: [],
      enabled: true,
      numberOfTeasers: 1,
      sort: null,
      teaserType: 'article' as TeaserType.Article, // explicit lowercase string to match enum value
      filter: {
        __typename: 'TeaserListBlockFilter',
        tags: ['test-tag-id'],
        tagObjects: [
          {
            __typename: 'Tag',
            id: nanoid(),
            tag: `lorem-ipsum`,
          },
        ],
      },
    },
    slots: [
      {
        type: TeaserSlotType.Manual,
        teaser: {
          type: TeaserType.Article,
          articleID: 'article_pool_100',
        } as unknown as typeof Teaser,
      },
      {
        type: TeaserSlotType.Autofill,
      },
    ],
    type: BlockType.TeaserSlots,
  } as unknown as BaseBlock<BlockType>;
};

const mockBlockWithAlignment = ({
  alignment = {
    i: nanoid(),
    x: 0,
    y: 0,
    w: 0,
    h: 0,
    static: false,
  },
  block = mockTeaserSlotsBlock() as unknown as BaseBlock<BlockType>,
} = {}): BlockWithAlignment =>
  ({
    alignment,
    block,
  }) as unknown as BlockWithAlignment;

type TeaserWithAlignment = {
  alignment: {
    i: string;
    x: number;
    y: number;
    w: number;
    h: number;
    static: boolean;
  };
  teaser: BaseBlock<BlockType>;
};

const mockTeaserWithAlignment = ({
  alignment = {
    i: nanoid(),
    x: 0,
    y: 0,
    w: 0,
    h: 0,
    static: false,
  },
  teaser = mockTeaserSlotsBlock() as unknown as BaseBlock<BlockType>,
} = {}): TeaserWithAlignment =>
  ({
    alignment,
    teaser,
  }) as unknown as TeaserWithAlignment;

const mockTeaserGridFlexBlock = ({
  blockStyle = undefined,
  flexTeasers = [] as TeaserWithAlignment[],
} = {}) =>
  ({
    type: BlockType.TeaserGridFlex,
    blockStyle,
    flexTeasers,
  }) as unknown as FlexBlock;

const mockArticleTeaser = ({ articleID = 'mock_article_id' } = {}) =>
  ({
    type: TeaserType.Article,
    articleID,
  }) as unknown as ArticleTeaser;

const revisionBlocks: BaseBlock<BlockType>[] = [
  mockFlexBlock({
    blocks: [
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlockWithManualTeaser() }),
    ],
  }),
  mockTeaserSlotsBlock() as unknown as BaseBlock<BlockType>,
  // teasers in grid-flex-block must not be repeated in teaser-slots-blocks
  mockTeaserGridFlexBlock({
    flexTeasers: [
      mockTeaserWithAlignment({
        teaser: mockArticleTeaser({
          articleID: 'article_pool_66',
        }) as unknown as BaseBlock<BlockType>,
      }),
      mockTeaserWithAlignment({
        teaser: mockArticleTeaser({
          articleID: 'article_pool_67',
        }) as unknown as BaseBlock<BlockType>,
      }),
    ],
  }) as unknown as BaseBlock<BlockType>,
  mockFlexBlock({
    blocks: [
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
      mockBlockWithAlignment({ block: mockTeaserSlotsBlock() }),
    ],
  }),
];

const mockEventService = {
  getEvents: jest.fn().mockResolvedValue({ nodes: [] }),
};

// simulate database with a fixed pool of articles
const ARTICLE_POOL = Array.from({ length: 150 }, (_, i) => ({
  id: `article_pool_${i + 1}`,
  title: `Article ${i + 1}`,
}));

const mockArticleService = {
  getArticles: jest.fn().mockImplementation(async ({ take, filter }) => {
    const excludedIds = filter?.excludeIds || [];

    // simulate async database delay with random timing to expose race conditions while loading teasers
    await new Promise(resolve => setTimeout(resolve, Math.random() * 50));

    // simulate database: return articles from pool that are NOT in excludeIds
    const availableArticles = ARTICLE_POOL.filter(
      a => !excludedIds.includes(a.id)
    );
    const articles = availableArticles.slice(0, take);

    return { nodes: articles };
  }),
};

const mockManualTeaserSlotsBlock = (articleID: string) =>
  ({
    autofillConfig: { enabled: false, teaserType: TeaserType.Article },
    slots: [
      {
        type: TeaserSlotType.Manual,
        teaser: mockArticleTeaser({ articleID }),
      },
    ],
    type: BlockType.TeaserSlots,
  }) as unknown as BaseBlock<BlockType>;

const mockBlockTemplateBlock = (templateID: string) =>
  ({
    type: BlockType.BlockTemplate,
    templateID,
  }) as unknown as BaseBlock<BlockType>;

let mockTemplates: Record<string, { id: string; blocks: unknown[] }> = {};

const mockBlockTemplateDataloader = {
  load: jest.fn(async (id: string) => mockTemplates[id] ?? null),
};

describe('SlotTeasersLoader', () => {
  let service: SlotTeasersLoader;

  beforeEach(async () => {
    jest.clearAllMocks();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        SlotTeasersLoader,
        { provide: EventService, useValue: mockEventService },
        { provide: ArticleService, useValue: mockArticleService },
        {
          provide: BlockTemplateDataloaderService,
          useValue: mockBlockTemplateDataloader,
        },
      ],
    }).compile();

    service = await module.resolve<SlotTeasersLoader>(SlotTeasersLoader);
  });

  const extractTeasers = (block: TeaserSlotsBlock): string[] => {
    const teaserIds: string[] = [];
    for (const t of block.teasers) {
      if (t && t.type === TeaserType.Article) {
        const teaser = t as ArticleTeaser;
        const id = teaser.article?.id || teaser.articleID;
        if (id) {
          teaserIds.push(id);
        }
      }
    }
    return teaserIds;
  };

  const processBlock = (block: BaseBlock<BlockType>) => {
    if (isFlexBlock(block)) {
      const teaserIds: string[] = [];
      for (const nestedBlock of (block as FlexBlock).blocks) {
        teaserIds.push(
          ...processBlock(
            (nestedBlock as BlockWithAlignment).block as BaseBlock<BlockType>
          )
        );
      }
      return teaserIds;
    }

    if (block.type === BlockType.BlockTemplate) {
      const teaserIds: string[] = [];
      for (const nestedBlock of (block as BlockTemplateBlock).template
        ?.blocks ?? []) {
        teaserIds.push(...processBlock(nestedBlock as BaseBlock<BlockType>));
      }
      return teaserIds;
    }

    if (isTeaserSlotsBlock(block)) {
      return extractTeasers(block as unknown as TeaserSlotsBlock);
    }

    return [];
  };

  const loadTeaserIds = async (blocks: BaseBlock<BlockType>[]) =>
    (await service.loadSlotTeasersIntoBlocks(blocks)).flatMap(block =>
      processBlock(block as BaseBlock<BlockType>)
    );

  const pool = (from: number, to: number) =>
    Array.from({ length: to - from + 1 }, (_, i) => `article_pool_${from + i}`);

  it('should autofill teaser slots nested in flex blocks', async () => {
    expect(
      await loadTeaserIds([
        mockFlexBlock({ blocks: [mockBlockWithAlignment()] }),
      ])
    ).toEqual(pool(1, 8));
  });

  describe('hidden blocks', () => {
    const hide = <T extends BaseBlock<BlockType>>(block: T) =>
      ({ ...block, disabled: true }) as T;

    it('should autofill teasers that are only placed manually in hidden blocks', async () => {
      const [, visible] = await service.loadSlotTeasersIntoBlocks([
        hide(mockManualTeaserSlotsBlock('article_pool_1')),
        mockTeaserSlotsBlock(),
      ]);

      expect(processBlock(visible as BaseBlock<BlockType>)).toEqual(pool(1, 8));
    });

    it('should not take autofill teasers away from visible blocks', async () => {
      const [hidden, visible] = await service.loadSlotTeasersIntoBlocks([
        hide(mockTeaserSlotsBlock()),
        mockTeaserSlotsBlock(),
      ]);

      // hidden blocks are still populated for the editor
      expect(processBlock(hidden as BaseBlock<BlockType>)).toEqual(pool(1, 8));
      expect(processBlock(visible as BaseBlock<BlockType>)).toEqual(pool(1, 8));
    });

    it('should treat blocks nested in hidden flex blocks and templates as hidden', async () => {
      mockTemplates = {
        manual: {
          id: 'manual',
          blocks: [mockManualTeaserSlotsBlock('article_pool_2')],
        },
      };

      const result = await service.loadSlotTeasersIntoBlocks([
        hide(
          mockFlexBlock({
            blocks: [
              mockBlockWithAlignment({
                block: mockManualTeaserSlotsBlock('article_pool_1'),
              }),
              mockBlockWithAlignment(),
            ],
          })
        ),
        hide(mockBlockTemplateBlock('manual')),
        mockTeaserSlotsBlock(),
      ]);

      expect(processBlock(result[2] as BaseBlock<BlockType>)).toEqual(
        pool(1, 8)
      );
    });

    it('should autofill teasers placed manually in hidden blocks of a template', async () => {
      mockTemplates = {
        mixed: {
          id: 'mixed',
          blocks: [
            hide(mockManualTeaserSlotsBlock('article_pool_1')),
            mockTeaserSlotsBlock(),
          ],
        },
      };

      expect(await loadTeaserIds([mockBlockTemplateBlock('mixed')])).toEqual([
        'article_pool_1',
        ...pool(1, 8),
      ]);
    });
  });

  describe('block templates', () => {
    beforeEach(() => {
      mockTemplates = {
        slots: {
          id: 'slots',
          blocks: [
            mockTeaserSlotsBlock(),
            mockTeaserSlotsBlockWithManualTeaser(),
          ],
        },
        manual: {
          id: 'manual',
          blocks: [mockManualTeaserSlotsBlock('article_pool_1')],
        },
        flex: {
          id: 'flex',
          blocks: [mockFlexBlock({ blocks: [mockBlockWithAlignment()] })],
        },
        nested: { id: 'nested', blocks: [mockBlockTemplateBlock('slots')] },
        circular: {
          id: 'circular',
          blocks: [mockBlockTemplateBlock('circular'), mockTeaserSlotsBlock()],
        },
      };
    });

    it('should populate the teaser slots of a template', async () => {
      const [block] = (await service.loadSlotTeasersIntoBlocks([
        mockBlockTemplateBlock('slots'),
      ])) as BlockTemplateBlock[];

      expect(processBlock(block)).toEqual([
        ...pool(1, 8),
        'article_pool_100',
        'article_pool_9',
      ]);
      expect(
        !!block.template && service.isPopulatedTemplate(block.template)
      ).toBe(true);
    });

    it('should not repeat teasers between templates and surrounding blocks', async () => {
      expect(
        await loadTeaserIds([
          mockTeaserSlotsBlock(),
          mockBlockTemplateBlock('manual'),
          mockTeaserSlotsBlock(),
        ])
      ).toEqual([...pool(2, 9), 'article_pool_1', ...pool(10, 17)]);
    });

    it('should populate templates nested in flex blocks and flex blocks nested in templates', async () => {
      expect(
        await loadTeaserIds([
          mockFlexBlock({
            blocks: [
              mockBlockWithAlignment({ block: mockBlockTemplateBlock('flex') }),
            ],
          }),
        ])
      ).toEqual(pool(1, 8));
    });

    it('should populate templates nested in templates', async () => {
      expect(await loadTeaserIds([mockBlockTemplateBlock('nested')])).toEqual([
        ...pool(1, 8),
        'article_pool_100',
        'article_pool_9',
      ]);
    });

    it('should not expand circular templates', async () => {
      const [block] = (await service.loadSlotTeasersIntoBlocks([
        mockBlockTemplateBlock('circular'),
      ])) as BlockTemplateBlock[];

      const [circular] = (block.template?.blocks ?? []) as BlockTemplateBlock[];

      expect(circular.template).toBeNull();
      expect(processBlock(block)).toEqual(pool(1, 8));
    });

    it('should keep unknown templates to be resolved as null', async () => {
      const [block] = (await service.loadSlotTeasersIntoBlocks([
        mockBlockTemplateBlock('deleted'),
      ])) as BlockTemplateBlock[];

      expect(block.template).toBeUndefined();
    });

    it('should populate a template queried on its own without sharing loaded teasers', async () => {
      expect(await loadTeaserIds([mockTeaserSlotsBlock()])).toEqual(pool(1, 8));

      const templateBlocks = await service.loadSlotTeasersIntoTemplateBlocks(
        mockTemplates['slots'].blocks as BaseBlock<BlockType>[]
      );

      expect(
        templateBlocks.flatMap(block =>
          processBlock(block as BaseBlock<BlockType>)
        )
      ).toEqual([...pool(1, 8), 'article_pool_100', 'article_pool_9']);

      expect(await loadTeaserIds([mockTeaserSlotsBlock()])).toEqual(
        pool(9, 16)
      );
    });
  });

  it('should return unique teasers', async () => {
    const result = await service.loadSlotTeasersIntoBlocks(revisionBlocks);
    const shouldBeUniqueTeaserIds: string[] = [];

    for (const block of result as BaseBlock<BlockType>[]) {
      shouldBeUniqueTeaserIds.push(...processBlock(block));
    }

    //console.log('shouldBeUniqueTeaserIds:', shouldBeUniqueTeaserIds);

    const unique = (x: string, i: number, arr: string[]) =>
      arr.indexOf(x) === i;

    const naturalSortAsc = (a: string, b: string) =>
      ('' + a).localeCompare(b, undefined, {
        numeric: true,
        sensitivity: 'base',
      });

    const filteredTeaserIds = shouldBeUniqueTeaserIds.filter(unique);
    const sortedTeaserIds = [...shouldBeUniqueTeaserIds].sort(naturalSortAsc);
    // in the sorted array, move id of manually added teaser (id 'article_pool_100')...
    // ...to its expected position (after 'article_pool_56')
    const manualTeaserId = 'article_pool_100';
    const indexOfManualTeaser = sortedTeaserIds.indexOf(manualTeaserId);
    if (indexOfManualTeaser > -1) {
      sortedTeaserIds.splice(indexOfManualTeaser, 1);
      const expectedIndex = shouldBeUniqueTeaserIds.indexOf(manualTeaserId);
      sortedTeaserIds.splice(expectedIndex, 0, manualTeaserId);
    }

    const hasItem66 = shouldBeUniqueTeaserIds.some(
      item => item === 'article_pool_66'
    );
    const hasItem67 = shouldBeUniqueTeaserIds.some(
      item => item === 'article_pool_67'
    );

    // teasers from grid-flex-block should not be repeated in autofilled teaser-slots-blocks
    expect(hasItem66).toBe(false);
    expect(hasItem67).toBe(false);

    //      1 teaser-slots-block x 8 slots --> 8 teasers
    // +    1 flex-blocks
    // +      7 teaser-slots-blocks x 8 slots --> 56 teasers
    // +      1 teaser-slots-blocks x (1 manual slot + 1 autofill slot) --> 2 teasers
    // +    1 flex-blocks x 7 teaser-slots-blocks x 8 slots --> 56 teasers
    // --------------------------------------------------------
    // =  122 teasers expected
    //
    expect(shouldBeUniqueTeaserIds.length).toEqual(122);

    // teaser ids should be in the order they were loaded into blocks
    expect(sortedTeaserIds.join(',')).toEqual(
      shouldBeUniqueTeaserIds.join(',')
    );

    // all ids should be unique
    expect(filteredTeaserIds).toEqual(shouldBeUniqueTeaserIds);

    // snapshot test the full structure
    expect(result).toMatchSnapshot();
  });
});
