version: '3'
services:
  oauth:
    image: oryd/hydra:latest
    ports:
      - "3010:4444"
      - "3011:4445"
    command:
      serve all --dangerous-force-http
    environment:
      URLS_SELF_ISSUER: "http://localhost:3010"
      URLS_SELF_PUBLIC: "http://localhost:3010"
      URLS_LOGIN: "http://localhost:3000/auth/wepublish/login"
      URLS_CONSENT: "http://localhost:3000/auth/wepublish/consent"
      URLS_LOGOUT: "http://localhost:3000/auth/wepublish/logout"
      URLS_ERROR: "http://localhost:3000/auth/wepublish/error"
      DSN: "postgres://wepublish:1234@db:5432/oauth?sslmode=disable"
      SECRETS_SYSTEM: "youReallyNeedToChangeThis"
      SERVER_ADMIN_CORS_ALLOWED_ORIGINS: '*'
  db:
    image: "postgres"
    ports:
      - "55555:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "oauth"
      POSTGRES_USER: "wepublish"
