FROM node:12.8.1-alpine

RUN apk add --no-cache python gcc g++ make

USER node

RUN mkdir -p /home/node/wepublish
WORKDIR /home/node/wepublish

COPY --chown=node:node package.json ./

RUN yarn install

COPY --chown=node:node ./dist/ ./dist/

ENV PORT=3005
EXPOSE 3005
CMD [ "node", "./dist/index.js" ]
