version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - default

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  database:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wepublish
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    image: dpage/pgadmin4:9.7
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 8000
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./.pgpass:/pgadmin4/.pgpass
    ports:
      - 8000:8000
    networks:
      - default
    depends_on:
      - database

  storage:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    entrypoint: ["/bin/sh"]
    command: ["-ec",
      "mkdir -p /data/wepublish-staff /data/wepublish-transformed; \
               exec minio server /data --console-address=:9001"]
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - default
    volumes:
      - storage_data:/data

volumes:
  database_data:
  storage_data:
