---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-api-config-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ include "helm.fullname" . }}-api-config-{{ .Release.Revision }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    {{- toYaml .Values.api.config | nindent 4 }}
    
