---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "helm.fullname" . }}-api
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-editor
  labels:
    app.kubernetes.io/name: {{ include "helm.fullname" . }}-editor
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.editor.type }}
  ports:
    - port: {{ .Values.service.editor.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm.name" . }}-editor
    app.kubernetes.io/instance: {{ .Release.Name }}
