FROM node:12.14.0-alpine

USER node
RUN mkdir -p /home/node/bajour
WORKDIR /home/node/bajour

COPY --chown=node:node package.json ./

RUN yarn install

COPY --chown=node:node tsconfig.json tsconfig.base.json webpack.config.ts .babelrc ./
COPY --chown=node:node ./scripts/ ./scripts/
COPY --chown=node:node ./src/ ./src/
COPY --chown=node:node ./static/ ./static/

RUN yarn build

ENV ADDRESS=0.0.0.0
ENV PORT=3000

EXPOSE 3000
CMD [ "node", "./dist/server/index.js" ]
