FROM node:12.14.0-alpine

USER node
RUN mkdir -p /home/node/wepublish
WORKDIR /home/node/wepublish

COPY --chown=node:node package.json ./

RUN yarn install --production

COPY --chown=node:node ./dist/ ./dist/
COPY --chown=node:node ./assets/ ./assets/
COPY --chown=node:node ./static/ ./static/


ENV PORT=5000
EXPOSE 5000
CMD [ "node", "./dist/server/index.js" ]
