// THIS FILE IS AUTOGENERATED, EDIT WITH CAUTION
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { FullImageFragment, FullImageUrLsFragment, ImageUrLsFragment, SquareImageUrLsFragment, SlimImageFragment, FullPeerImageFragment } from './image.generated';
import { FullPropertyFragment } from './properties.generated';
import { gql } from '@apollo/client';
import { FullImageFragmentDoc, FullImageUrLsFragmentDoc, ImageUrLsFragmentDoc, SquareImageUrLsFragmentDoc, SlimImageFragmentDoc, FullPeerImageFragmentDoc } from './image.generated';
import { FullPropertyFragmentDoc } from './properties.generated';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type FullPaymentMethodFragment = { __typename?: 'PaymentMethod', id: string, paymentProviderID: string, name: string, slug: string, description: string, gracePeriod: number, image?: (
    { __typename?: 'Image' }
    & FullImageFragment
  ) | null };

export type FullAvailablePaymentMethodFragment = { __typename?: 'AvailablePaymentMethod', paymentPeriodicities: Array<Types.PaymentPeriodicity>, forceAutoRenewal: boolean, paymentMethods: Array<(
    { __typename?: 'PaymentMethod' }
    & FullPaymentMethodFragment
  )> };

export type FullGoodieFragment = { __typename?: 'Goodie', id: string, name: string, description?: RichtextJSONDocument | null, stock?: number | null, image?: (
    { __typename?: 'Image' }
    & FullImageFragment
  ) | null };

export type FullMemberPlanFragment = { __typename?: 'MemberPlan', id: string, slug: string, name: string, tags?: Array<string> | null, description?: RichtextJSONDocument | null, shortDescription?: RichtextJSONDocument | null, amountPerMonthMin: number, amountPerMonthMax?: number | null, amountPerMonthTarget?: number | null, defaultPaymentPeriodicity?: Types.PaymentPeriodicity | null, currency: Types.Currency, extendable: boolean, productType: Types.ProductType, successPageId?: string | null, failPageId?: string | null, confirmationPageId?: string | null, image?: (
    { __typename?: 'Image' }
    & FullImageFragment
  ) | null, periodicityPricing?: Array<{ __typename?: 'PeriodicityPrice', periodicity: Types.PaymentPeriodicity, label?: string | null, amountMin?: number | null, amountTarget?: number | null, amountMax?: number | null }> | null, availablePaymentMethods: Array<(
    { __typename?: 'AvailablePaymentMethod' }
    & FullAvailablePaymentMethodFragment
  )>, successPage?: { __typename?: 'Page', url: string } | null, failPage?: { __typename?: 'Page', url: string } | null, confirmationPage?: { __typename?: 'Page', url: string } | null, goodies: Array<(
    { __typename?: 'Goodie' }
    & FullGoodieFragment
  )> };

export type FullPaymentFragment = { __typename?: 'Payment', id: string, intentSecret: string, state: Types.PaymentState, paymentMethod: (
    { __typename?: 'PaymentMethod' }
    & FullPaymentMethodFragment
  ) };

export type FullSubscriptionDeactivationFragment = { __typename?: 'SubscriptionDeactivation', date: string, reason: Types.SubscriptionDeactivationReason };

export type FullSubscriptionFragment = { __typename?: 'PublicSubscription', id: string, url: string, paymentPeriodicity: Types.PaymentPeriodicity, monthlyAmount: number, autoRenew: boolean, startsAt: string, extendable: boolean, externalReward?: string | null, paidUntil?: string | null, canExtend: boolean, isActive: boolean, paymentMethod: (
    { __typename?: 'PaymentMethod' }
    & FullPaymentMethodFragment
  ), deactivation?: (
    { __typename?: 'SubscriptionDeactivation' }
    & FullSubscriptionDeactivationFragment
  ) | null, memberPlan: (
    { __typename?: 'MemberPlan' }
    & FullMemberPlanFragment
  ), properties: Array<(
    { __typename?: 'Property' }
    & FullPropertyFragment
  )>, goodie?: (
    { __typename?: 'Goodie' }
    & FullGoodieFragment
  ) | null };

export type FullInvoiceItemFragment = { __typename?: 'InvoiceItem', createdAt: string, modifiedAt: string, name: string, description?: string | null, quantity: number, amount: number, total: number };

export type FullInvoiceFragment = { __typename?: 'Invoice', id: string, createdAt: string, modifiedAt: string, mail: string, paidAt?: string | null, dueAt: string, canceledAt?: string | null, subscriptionID?: string | null, description?: string | null, total: number, subscription?: (
    { __typename?: 'PublicSubscription' }
    & FullSubscriptionFragment
  ) | null, items: Array<(
    { __typename?: 'InvoiceItem' }
    & FullInvoiceItemFragment
  )> };

export type CreateSubscriptionInfoQueryVariables = Types.Exact<{
  memberPlanId: Types.Scalars['String'];
  discountCode?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type CreateSubscriptionInfoQuery = { __typename?: 'Query', createSubscriptionInfo: { __typename?: 'CreateSubscriptionInfo', discountCodeValid?: boolean | null, discountPercent?: number | null } };

export type SubscribeMutationVariables = Types.Exact<{
  memberPlanId?: Types.InputMaybe<Types.Scalars['String']>;
  memberPlanSlug?: Types.InputMaybe<Types.Scalars['Slug']>;
  autoRenew: Types.Scalars['Boolean'];
  paymentPeriodicity: Types.PaymentPeriodicity;
  monthlyAmount: Types.Scalars['Float'];
  paymentMethodId?: Types.InputMaybe<Types.Scalars['String']>;
  paymentMethodSlug?: Types.InputMaybe<Types.Scalars['Slug']>;
  subscriptionProperties?: Types.InputMaybe<Array<Types.PropertyInput> | Types.PropertyInput>;
  successURL?: Types.InputMaybe<Types.Scalars['String']>;
  failureURL?: Types.InputMaybe<Types.Scalars['String']>;
  deactivateSubscriptionId?: Types.InputMaybe<Types.Scalars['String']>;
  discountCode?: Types.InputMaybe<Types.Scalars['String']>;
  goodieId?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type SubscribeMutation = { __typename?: 'Mutation', createUserSubscription: (
    { __typename?: 'Payment' }
    & FullPaymentFragment
  ) };

export type ResubscribeMutationVariables = Types.Exact<{
  userId?: Types.InputMaybe<Types.Scalars['String']>;
  memberPlanId?: Types.InputMaybe<Types.Scalars['String']>;
  memberPlanSlug?: Types.InputMaybe<Types.Scalars['Slug']>;
  autoRenew: Types.Scalars['Boolean'];
  paymentPeriodicity: Types.PaymentPeriodicity;
  monthlyAmount: Types.Scalars['Float'];
  paymentMethodId?: Types.InputMaybe<Types.Scalars['String']>;
  paymentMethodSlug?: Types.InputMaybe<Types.Scalars['Slug']>;
  subscriptionProperties?: Types.InputMaybe<Array<Types.PropertyInput> | Types.PropertyInput>;
  discountCode?: Types.InputMaybe<Types.Scalars['String']>;
  goodieId?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type ResubscribeMutation = { __typename?: 'Mutation', createUserSubscriptionWithConfirmation: boolean };

export type UpgradeMutationVariables = Types.Exact<{
  subscriptionId: Types.Scalars['String'];
  memberPlanId: Types.Scalars['String'];
  paymentMethodId: Types.Scalars['String'];
  monthlyAmount: Types.Scalars['Float'];
  goodieId?: Types.InputMaybe<Types.Scalars['String']>;
  successURL?: Types.InputMaybe<Types.Scalars['String']>;
  failureURL?: Types.InputMaybe<Types.Scalars['String']>;
  discountCode?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type UpgradeMutation = { __typename?: 'Mutation', upgradeUserSubscription: (
    { __typename?: 'Payment' }
    & FullPaymentFragment
  ) };

export type PayInvoiceMutationVariables = Types.Exact<{
  invoiceId: Types.Scalars['String'];
  paymentMethodId?: Types.InputMaybe<Types.Scalars['String']>;
  paymentMethodSlug?: Types.InputMaybe<Types.Scalars['Slug']>;
  successURL?: Types.InputMaybe<Types.Scalars['String']>;
  failureURL?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type PayInvoiceMutation = { __typename?: 'Mutation', createPaymentFromInvoice?: (
    { __typename?: 'Payment' }
    & FullPaymentFragment
  ) | null };

export type PaySubscriptionMutationVariables = Types.Exact<{
  subscriptionId: Types.Scalars['String'];
  successURL?: Types.InputMaybe<Types.Scalars['String']>;
  failureURL?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type PaySubscriptionMutation = { __typename?: 'Mutation', createPaymentFromSubscription?: (
    { __typename?: 'Payment' }
    & FullPaymentFragment
  ) | null };

export type CancelSubscriptionMutationVariables = Types.Exact<{
  subscriptionId: Types.Scalars['String'];
}>;


export type CancelSubscriptionMutation = { __typename?: 'Mutation', cancelUserSubscription?: (
    { __typename?: 'PublicSubscription' }
    & FullSubscriptionFragment
  ) | null };

export type ExtendSubscriptionMutationVariables = Types.Exact<{
  subscriptionId: Types.Scalars['String'];
  successURL?: Types.InputMaybe<Types.Scalars['String']>;
  failureURL?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type ExtendSubscriptionMutation = { __typename?: 'Mutation', extendUserSubscription: (
    { __typename?: 'Payment' }
    & FullPaymentFragment
  ) };

export type InvoicesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type InvoicesQuery = { __typename?: 'Query', userInvoices: Array<(
    { __typename?: 'Invoice' }
    & FullInvoiceFragment
  )> };

export type SubscriptionsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type SubscriptionsQuery = { __typename?: 'Query', userSubscriptions: Array<(
    { __typename?: 'PublicSubscription' }
    & FullSubscriptionFragment
  )> };

export type CheckInvoiceStatusQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type CheckInvoiceStatusQuery = { __typename?: 'Query', checkInvoiceStatus: (
    { __typename?: 'Invoice' }
    & FullInvoiceFragment
  ) };

export type MemberPlanListQueryVariables = Types.Exact<{
  filter?: Types.InputMaybe<Types.MemberPlanFilter>;
  cursorId?: Types.InputMaybe<Types.Scalars['String']>;
  take?: Types.InputMaybe<Types.Scalars['Int']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  order?: Types.InputMaybe<Types.SortOrder>;
  sort?: Types.InputMaybe<Types.MemberPlanSort>;
}>;


export type MemberPlanListQuery = { __typename?: 'Query', memberPlans: { __typename?: 'PaginatedMemberPlans', totalCount: number, nodes: Array<(
      { __typename?: 'MemberPlan' }
      & FullMemberPlanFragment
    )>, pageInfo: { __typename?: 'PageInfo', startCursor?: string | null, endCursor?: string | null, hasNextPage: boolean, hasPreviousPage: boolean } } };

export type RevenueQueryVariables = Types.Exact<{
  start: Types.Scalars['DateTime'];
  end?: Types.InputMaybe<Types.Scalars['DateTime']>;
}>;


export type RevenueQuery = { __typename?: 'Query', revenue: Array<{ __typename?: 'DashboardInvoice', amount: number, paidAt?: string | null, memberPlan?: string | null }> };

export type NewSubscribersQueryVariables = Types.Exact<{
  start: Types.Scalars['DateTime'];
  end?: Types.InputMaybe<Types.Scalars['DateTime']>;
}>;


export type NewSubscribersQuery = { __typename?: 'Query', newSubscribers: Array<{ __typename?: 'DashboardSubscription', monthlyAmount: number, memberPlan: string }> };

export type UpgradeSubscriptionInfoQueryVariables = Types.Exact<{
  memberPlanId: Types.Scalars['String'];
  subscriptionId: Types.Scalars['String'];
  discountCode?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type UpgradeSubscriptionInfoQuery = { __typename?: 'Query', upgradeUserSubscriptionInfo: { __typename?: 'UpgradeSubscription', discountAmount: number, discountPercent?: number | null, discountCodeValid?: boolean | null } };

export type FullDiscountCodeFragment = { __typename?: 'DiscountCode', id: string, code: string, discountPercent: number, validFrom: string, validTo: string, memberPlanId: string, memberPlan: { __typename?: 'MemberPlan', id: string, name: string } };

export type DiscountCodeListQueryVariables = Types.Exact<{
  filter?: Types.InputMaybe<Types.DiscountCodeFilter>;
  cursorId?: Types.InputMaybe<Types.Scalars['String']>;
  take?: Types.InputMaybe<Types.Scalars['Int']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  order?: Types.InputMaybe<Types.SortOrder>;
  sort?: Types.InputMaybe<Types.DiscountCodesort>;
}>;


export type DiscountCodeListQuery = { __typename?: 'Query', discountCodes: { __typename?: 'PaginatedDiscountCodes', totalCount: number, nodes: Array<(
      { __typename?: 'DiscountCode' }
      & FullDiscountCodeFragment
    )>, pageInfo: { __typename?: 'PageInfo', startCursor?: string | null, endCursor?: string | null, hasNextPage: boolean, hasPreviousPage: boolean } } };

export const FullPaymentMethodFragmentDoc = gql`
    fragment FullPaymentMethod on PaymentMethod {
  id
  paymentProviderID
  name
  slug
  description
  gracePeriod
  image {
    ...FullImage
  }
}
    `;
export const FullPaymentFragmentDoc = gql`
    fragment FullPayment on Payment {
  id
  intentSecret
  state
  paymentMethod {
    ...FullPaymentMethod
  }
}
    `;
export const FullSubscriptionDeactivationFragmentDoc = gql`
    fragment FullSubscriptionDeactivation on SubscriptionDeactivation {
  date
  reason
}
    `;
export const FullAvailablePaymentMethodFragmentDoc = gql`
    fragment FullAvailablePaymentMethod on AvailablePaymentMethod {
  paymentMethods {
    ...FullPaymentMethod
  }
  paymentPeriodicities
  forceAutoRenewal
}
    `;
export const FullGoodieFragmentDoc = gql`
    fragment FullGoodie on Goodie {
  id
  name
  description
  stock
  image {
    ...FullImage
  }
}
    `;
export const FullMemberPlanFragmentDoc = gql`
    fragment FullMemberPlan on MemberPlan {
  id
  slug
  name
  tags
  description
  shortDescription
  image {
    ...FullImage
  }
  amountPerMonthMin
  amountPerMonthMax
  amountPerMonthTarget
  periodicityPricing {
    periodicity
    label
    amountMin
    amountTarget
    amountMax
  }
  defaultPaymentPeriodicity
  currency
  availablePaymentMethods {
    ...FullAvailablePaymentMethod
  }
  extendable
  productType
  successPageId
  successPage {
    url
  }
  failPageId
  failPage {
    url
  }
  confirmationPageId
  confirmationPage {
    url
  }
  goodies {
    ...FullGoodie
  }
}
    `;
export const FullSubscriptionFragmentDoc = gql`
    fragment FullSubscription on PublicSubscription {
  id
  url
  paymentPeriodicity
  monthlyAmount
  autoRenew
  startsAt
  extendable
  externalReward
  paidUntil
  paymentMethod {
    ...FullPaymentMethod
  }
  deactivation {
    ...FullSubscriptionDeactivation
  }
  memberPlan {
    ...FullMemberPlan
  }
  properties {
    ...FullProperty
  }
  goodie {
    ...FullGoodie
  }
  canExtend
  isActive
}
    `;
export const FullInvoiceItemFragmentDoc = gql`
    fragment FullInvoiceItem on InvoiceItem {
  createdAt
  modifiedAt
  name
  description
  quantity
  amount
  total
}
    `;
export const FullInvoiceFragmentDoc = gql`
    fragment FullInvoice on Invoice {
  id
  createdAt
  modifiedAt
  mail
  paidAt
  dueAt
  canceledAt
  subscriptionID
  subscription {
    ...FullSubscription
  }
  description
  items {
    ...FullInvoiceItem
  }
  total
}
    `;
export const FullDiscountCodeFragmentDoc = gql`
    fragment FullDiscountCode on DiscountCode {
  id
  code
  discountPercent
  validFrom
  validTo
  memberPlanId
  memberPlan {
    id
    name
  }
}
    `;
export const CreateSubscriptionInfoDocument = gql`
    query CreateSubscriptionInfo($memberPlanId: String!, $discountCode: String) {
  createSubscriptionInfo(memberPlanId: $memberPlanId, discountCode: $discountCode) {
    discountCodeValid
    discountPercent
  }
}
    `;

/**
 * __useCreateSubscriptionInfoQuery__
 *
 * To run a query within a React component, call `useCreateSubscriptionInfoQuery` and pass it any options that fit your needs.
 * When your component renders, `useCreateSubscriptionInfoQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCreateSubscriptionInfoQuery({
 *   variables: {
 *      memberPlanId: // value for 'memberPlanId'
 *      discountCode: // value for 'discountCode'
 *   },
 * });
 */
export function useCreateSubscriptionInfoQuery(baseOptions: Apollo.QueryHookOptions<CreateSubscriptionInfoQuery, CreateSubscriptionInfoQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CreateSubscriptionInfoQuery, CreateSubscriptionInfoQueryVariables>(CreateSubscriptionInfoDocument, options);
      }
export function useCreateSubscriptionInfoLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CreateSubscriptionInfoQuery, CreateSubscriptionInfoQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CreateSubscriptionInfoQuery, CreateSubscriptionInfoQueryVariables>(CreateSubscriptionInfoDocument, options);
        }
export type CreateSubscriptionInfoQueryHookResult = ReturnType<typeof useCreateSubscriptionInfoQuery>;
export type CreateSubscriptionInfoLazyQueryHookResult = ReturnType<typeof useCreateSubscriptionInfoLazyQuery>;
export type CreateSubscriptionInfoQueryResult = Apollo.QueryResult<CreateSubscriptionInfoQuery, CreateSubscriptionInfoQueryVariables>;
export const SubscribeDocument = gql`
    mutation Subscribe($memberPlanId: String, $memberPlanSlug: Slug, $autoRenew: Boolean!, $paymentPeriodicity: PaymentPeriodicity!, $monthlyAmount: Float!, $paymentMethodId: String, $paymentMethodSlug: Slug, $subscriptionProperties: [PropertyInput!], $successURL: String, $failureURL: String, $deactivateSubscriptionId: String, $discountCode: String, $goodieId: String) {
  createUserSubscription(
    memberPlanID: $memberPlanId
    memberPlanSlug: $memberPlanSlug
    autoRenew: $autoRenew
    paymentPeriodicity: $paymentPeriodicity
    monthlyAmount: $monthlyAmount
    paymentMethodID: $paymentMethodId
    paymentMethodSlug: $paymentMethodSlug
    subscriptionProperties: $subscriptionProperties
    successURL: $successURL
    failureURL: $failureURL
    deactivateSubscriptionId: $deactivateSubscriptionId
    discountCode: $discountCode
    goodieId: $goodieId
  ) {
    ...FullPayment
  }
}
    ${FullPaymentFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}`;
export type SubscribeMutationFn = Apollo.MutationFunction<SubscribeMutation, SubscribeMutationVariables>;

/**
 * __useSubscribeMutation__
 *
 * To run a mutation, you first call `useSubscribeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSubscribeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [subscribeMutation, { data, loading, error }] = useSubscribeMutation({
 *   variables: {
 *      memberPlanId: // value for 'memberPlanId'
 *      memberPlanSlug: // value for 'memberPlanSlug'
 *      autoRenew: // value for 'autoRenew'
 *      paymentPeriodicity: // value for 'paymentPeriodicity'
 *      monthlyAmount: // value for 'monthlyAmount'
 *      paymentMethodId: // value for 'paymentMethodId'
 *      paymentMethodSlug: // value for 'paymentMethodSlug'
 *      subscriptionProperties: // value for 'subscriptionProperties'
 *      successURL: // value for 'successURL'
 *      failureURL: // value for 'failureURL'
 *      deactivateSubscriptionId: // value for 'deactivateSubscriptionId'
 *      discountCode: // value for 'discountCode'
 *      goodieId: // value for 'goodieId'
 *   },
 * });
 */
export function useSubscribeMutation(baseOptions?: Apollo.MutationHookOptions<SubscribeMutation, SubscribeMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<SubscribeMutation, SubscribeMutationVariables>(SubscribeDocument, options);
      }
export type SubscribeMutationHookResult = ReturnType<typeof useSubscribeMutation>;
export type SubscribeMutationResult = Apollo.MutationResult<SubscribeMutation>;
export type SubscribeMutationOptions = Apollo.BaseMutationOptions<SubscribeMutation, SubscribeMutationVariables>;
export const ResubscribeDocument = gql`
    mutation Resubscribe($userId: String, $memberPlanId: String, $memberPlanSlug: Slug, $autoRenew: Boolean!, $paymentPeriodicity: PaymentPeriodicity!, $monthlyAmount: Float!, $paymentMethodId: String, $paymentMethodSlug: Slug, $subscriptionProperties: [PropertyInput!], $discountCode: String, $goodieId: String) {
  createUserSubscriptionWithConfirmation(
    userId: $userId
    memberPlanID: $memberPlanId
    memberPlanSlug: $memberPlanSlug
    autoRenew: $autoRenew
    paymentPeriodicity: $paymentPeriodicity
    monthlyAmount: $monthlyAmount
    paymentMethodID: $paymentMethodId
    paymentMethodSlug: $paymentMethodSlug
    subscriptionProperties: $subscriptionProperties
    discountCode: $discountCode
    goodieId: $goodieId
  )
}
    `;
export type ResubscribeMutationFn = Apollo.MutationFunction<ResubscribeMutation, ResubscribeMutationVariables>;

/**
 * __useResubscribeMutation__
 *
 * To run a mutation, you first call `useResubscribeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useResubscribeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [resubscribeMutation, { data, loading, error }] = useResubscribeMutation({
 *   variables: {
 *      userId: // value for 'userId'
 *      memberPlanId: // value for 'memberPlanId'
 *      memberPlanSlug: // value for 'memberPlanSlug'
 *      autoRenew: // value for 'autoRenew'
 *      paymentPeriodicity: // value for 'paymentPeriodicity'
 *      monthlyAmount: // value for 'monthlyAmount'
 *      paymentMethodId: // value for 'paymentMethodId'
 *      paymentMethodSlug: // value for 'paymentMethodSlug'
 *      subscriptionProperties: // value for 'subscriptionProperties'
 *      discountCode: // value for 'discountCode'
 *      goodieId: // value for 'goodieId'
 *   },
 * });
 */
export function useResubscribeMutation(baseOptions?: Apollo.MutationHookOptions<ResubscribeMutation, ResubscribeMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<ResubscribeMutation, ResubscribeMutationVariables>(ResubscribeDocument, options);
      }
export type ResubscribeMutationHookResult = ReturnType<typeof useResubscribeMutation>;
export type ResubscribeMutationResult = Apollo.MutationResult<ResubscribeMutation>;
export type ResubscribeMutationOptions = Apollo.BaseMutationOptions<ResubscribeMutation, ResubscribeMutationVariables>;
export const UpgradeDocument = gql`
    mutation Upgrade($subscriptionId: String!, $memberPlanId: String!, $paymentMethodId: String!, $monthlyAmount: Float!, $goodieId: String, $successURL: String, $failureURL: String, $discountCode: String) {
  upgradeUserSubscription(
    subscriptionId: $subscriptionId
    memberPlanId: $memberPlanId
    paymentMethodId: $paymentMethodId
    monthlyAmount: $monthlyAmount
    goodieId: $goodieId
    successURL: $successURL
    failureURL: $failureURL
    discountCode: $discountCode
  ) {
    ...FullPayment
  }
}
    ${FullPaymentFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}`;
export type UpgradeMutationFn = Apollo.MutationFunction<UpgradeMutation, UpgradeMutationVariables>;

/**
 * __useUpgradeMutation__
 *
 * To run a mutation, you first call `useUpgradeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpgradeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [upgradeMutation, { data, loading, error }] = useUpgradeMutation({
 *   variables: {
 *      subscriptionId: // value for 'subscriptionId'
 *      memberPlanId: // value for 'memberPlanId'
 *      paymentMethodId: // value for 'paymentMethodId'
 *      monthlyAmount: // value for 'monthlyAmount'
 *      goodieId: // value for 'goodieId'
 *      successURL: // value for 'successURL'
 *      failureURL: // value for 'failureURL'
 *      discountCode: // value for 'discountCode'
 *   },
 * });
 */
export function useUpgradeMutation(baseOptions?: Apollo.MutationHookOptions<UpgradeMutation, UpgradeMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpgradeMutation, UpgradeMutationVariables>(UpgradeDocument, options);
      }
export type UpgradeMutationHookResult = ReturnType<typeof useUpgradeMutation>;
export type UpgradeMutationResult = Apollo.MutationResult<UpgradeMutation>;
export type UpgradeMutationOptions = Apollo.BaseMutationOptions<UpgradeMutation, UpgradeMutationVariables>;
export const PayInvoiceDocument = gql`
    mutation PayInvoice($invoiceId: String!, $paymentMethodId: String, $paymentMethodSlug: Slug, $successURL: String, $failureURL: String) {
  createPaymentFromInvoice(
    input: {invoiceID: $invoiceId, paymentMethodID: $paymentMethodId, paymentMethodSlug: $paymentMethodSlug, successURL: $successURL, failureURL: $failureURL}
  ) {
    ...FullPayment
  }
}
    ${FullPaymentFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}`;
export type PayInvoiceMutationFn = Apollo.MutationFunction<PayInvoiceMutation, PayInvoiceMutationVariables>;

/**
 * __usePayInvoiceMutation__
 *
 * To run a mutation, you first call `usePayInvoiceMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `usePayInvoiceMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [payInvoiceMutation, { data, loading, error }] = usePayInvoiceMutation({
 *   variables: {
 *      invoiceId: // value for 'invoiceId'
 *      paymentMethodId: // value for 'paymentMethodId'
 *      paymentMethodSlug: // value for 'paymentMethodSlug'
 *      successURL: // value for 'successURL'
 *      failureURL: // value for 'failureURL'
 *   },
 * });
 */
export function usePayInvoiceMutation(baseOptions?: Apollo.MutationHookOptions<PayInvoiceMutation, PayInvoiceMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<PayInvoiceMutation, PayInvoiceMutationVariables>(PayInvoiceDocument, options);
      }
export type PayInvoiceMutationHookResult = ReturnType<typeof usePayInvoiceMutation>;
export type PayInvoiceMutationResult = Apollo.MutationResult<PayInvoiceMutation>;
export type PayInvoiceMutationOptions = Apollo.BaseMutationOptions<PayInvoiceMutation, PayInvoiceMutationVariables>;
export const PaySubscriptionDocument = gql`
    mutation PaySubscription($subscriptionId: String!, $successURL: String, $failureURL: String) {
  createPaymentFromSubscription(
    subscriptionId: $subscriptionId
    successURL: $successURL
    failureURL: $failureURL
  ) {
    ...FullPayment
  }
}
    ${FullPaymentFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}`;
export type PaySubscriptionMutationFn = Apollo.MutationFunction<PaySubscriptionMutation, PaySubscriptionMutationVariables>;

/**
 * __usePaySubscriptionMutation__
 *
 * To run a mutation, you first call `usePaySubscriptionMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `usePaySubscriptionMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [paySubscriptionMutation, { data, loading, error }] = usePaySubscriptionMutation({
 *   variables: {
 *      subscriptionId: // value for 'subscriptionId'
 *      successURL: // value for 'successURL'
 *      failureURL: // value for 'failureURL'
 *   },
 * });
 */
export function usePaySubscriptionMutation(baseOptions?: Apollo.MutationHookOptions<PaySubscriptionMutation, PaySubscriptionMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<PaySubscriptionMutation, PaySubscriptionMutationVariables>(PaySubscriptionDocument, options);
      }
export type PaySubscriptionMutationHookResult = ReturnType<typeof usePaySubscriptionMutation>;
export type PaySubscriptionMutationResult = Apollo.MutationResult<PaySubscriptionMutation>;
export type PaySubscriptionMutationOptions = Apollo.BaseMutationOptions<PaySubscriptionMutation, PaySubscriptionMutationVariables>;
export const CancelSubscriptionDocument = gql`
    mutation CancelSubscription($subscriptionId: String!) {
  cancelUserSubscription(id: $subscriptionId) {
    ...FullSubscription
  }
}
    ${FullSubscriptionFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}
${FullSubscriptionDeactivationFragmentDoc}
${FullMemberPlanFragmentDoc}
${FullAvailablePaymentMethodFragmentDoc}
${FullGoodieFragmentDoc}
${FullPropertyFragmentDoc}`;
export type CancelSubscriptionMutationFn = Apollo.MutationFunction<CancelSubscriptionMutation, CancelSubscriptionMutationVariables>;

/**
 * __useCancelSubscriptionMutation__
 *
 * To run a mutation, you first call `useCancelSubscriptionMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCancelSubscriptionMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [cancelSubscriptionMutation, { data, loading, error }] = useCancelSubscriptionMutation({
 *   variables: {
 *      subscriptionId: // value for 'subscriptionId'
 *   },
 * });
 */
export function useCancelSubscriptionMutation(baseOptions?: Apollo.MutationHookOptions<CancelSubscriptionMutation, CancelSubscriptionMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CancelSubscriptionMutation, CancelSubscriptionMutationVariables>(CancelSubscriptionDocument, options);
      }
export type CancelSubscriptionMutationHookResult = ReturnType<typeof useCancelSubscriptionMutation>;
export type CancelSubscriptionMutationResult = Apollo.MutationResult<CancelSubscriptionMutation>;
export type CancelSubscriptionMutationOptions = Apollo.BaseMutationOptions<CancelSubscriptionMutation, CancelSubscriptionMutationVariables>;
export const ExtendSubscriptionDocument = gql`
    mutation ExtendSubscription($subscriptionId: String!, $successURL: String, $failureURL: String) {
  extendUserSubscription(
    subscriptionId: $subscriptionId
    successURL: $successURL
    failureURL: $failureURL
  ) {
    ...FullPayment
  }
}
    ${FullPaymentFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}`;
export type ExtendSubscriptionMutationFn = Apollo.MutationFunction<ExtendSubscriptionMutation, ExtendSubscriptionMutationVariables>;

/**
 * __useExtendSubscriptionMutation__
 *
 * To run a mutation, you first call `useExtendSubscriptionMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useExtendSubscriptionMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [extendSubscriptionMutation, { data, loading, error }] = useExtendSubscriptionMutation({
 *   variables: {
 *      subscriptionId: // value for 'subscriptionId'
 *      successURL: // value for 'successURL'
 *      failureURL: // value for 'failureURL'
 *   },
 * });
 */
export function useExtendSubscriptionMutation(baseOptions?: Apollo.MutationHookOptions<ExtendSubscriptionMutation, ExtendSubscriptionMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<ExtendSubscriptionMutation, ExtendSubscriptionMutationVariables>(ExtendSubscriptionDocument, options);
      }
export type ExtendSubscriptionMutationHookResult = ReturnType<typeof useExtendSubscriptionMutation>;
export type ExtendSubscriptionMutationResult = Apollo.MutationResult<ExtendSubscriptionMutation>;
export type ExtendSubscriptionMutationOptions = Apollo.BaseMutationOptions<ExtendSubscriptionMutation, ExtendSubscriptionMutationVariables>;
export const InvoicesDocument = gql`
    query Invoices {
  userInvoices {
    ...FullInvoice
  }
}
    ${FullInvoiceFragmentDoc}
${FullSubscriptionFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}
${FullSubscriptionDeactivationFragmentDoc}
${FullMemberPlanFragmentDoc}
${FullAvailablePaymentMethodFragmentDoc}
${FullGoodieFragmentDoc}
${FullPropertyFragmentDoc}
${FullInvoiceItemFragmentDoc}`;

/**
 * __useInvoicesQuery__
 *
 * To run a query within a React component, call `useInvoicesQuery` and pass it any options that fit your needs.
 * When your component renders, `useInvoicesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useInvoicesQuery({
 *   variables: {
 *   },
 * });
 */
export function useInvoicesQuery(baseOptions?: Apollo.QueryHookOptions<InvoicesQuery, InvoicesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<InvoicesQuery, InvoicesQueryVariables>(InvoicesDocument, options);
      }
export function useInvoicesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<InvoicesQuery, InvoicesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<InvoicesQuery, InvoicesQueryVariables>(InvoicesDocument, options);
        }
export type InvoicesQueryHookResult = ReturnType<typeof useInvoicesQuery>;
export type InvoicesLazyQueryHookResult = ReturnType<typeof useInvoicesLazyQuery>;
export type InvoicesQueryResult = Apollo.QueryResult<InvoicesQuery, InvoicesQueryVariables>;
export const SubscriptionsDocument = gql`
    query Subscriptions {
  userSubscriptions {
    ...FullSubscription
  }
}
    ${FullSubscriptionFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}
${FullSubscriptionDeactivationFragmentDoc}
${FullMemberPlanFragmentDoc}
${FullAvailablePaymentMethodFragmentDoc}
${FullGoodieFragmentDoc}
${FullPropertyFragmentDoc}`;

/**
 * __useSubscriptionsQuery__
 *
 * To run a query within a React component, call `useSubscriptionsQuery` and pass it any options that fit your needs.
 * When your component renders, `useSubscriptionsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSubscriptionsQuery({
 *   variables: {
 *   },
 * });
 */
export function useSubscriptionsQuery(baseOptions?: Apollo.QueryHookOptions<SubscriptionsQuery, SubscriptionsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<SubscriptionsQuery, SubscriptionsQueryVariables>(SubscriptionsDocument, options);
      }
export function useSubscriptionsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SubscriptionsQuery, SubscriptionsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<SubscriptionsQuery, SubscriptionsQueryVariables>(SubscriptionsDocument, options);
        }
export type SubscriptionsQueryHookResult = ReturnType<typeof useSubscriptionsQuery>;
export type SubscriptionsLazyQueryHookResult = ReturnType<typeof useSubscriptionsLazyQuery>;
export type SubscriptionsQueryResult = Apollo.QueryResult<SubscriptionsQuery, SubscriptionsQueryVariables>;
export const CheckInvoiceStatusDocument = gql`
    query CheckInvoiceStatus($id: String!) {
  checkInvoiceStatus(id: $id) {
    ...FullInvoice
  }
}
    ${FullInvoiceFragmentDoc}
${FullSubscriptionFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}
${FullSubscriptionDeactivationFragmentDoc}
${FullMemberPlanFragmentDoc}
${FullAvailablePaymentMethodFragmentDoc}
${FullGoodieFragmentDoc}
${FullPropertyFragmentDoc}
${FullInvoiceItemFragmentDoc}`;

/**
 * __useCheckInvoiceStatusQuery__
 *
 * To run a query within a React component, call `useCheckInvoiceStatusQuery` and pass it any options that fit your needs.
 * When your component renders, `useCheckInvoiceStatusQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCheckInvoiceStatusQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useCheckInvoiceStatusQuery(baseOptions: Apollo.QueryHookOptions<CheckInvoiceStatusQuery, CheckInvoiceStatusQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CheckInvoiceStatusQuery, CheckInvoiceStatusQueryVariables>(CheckInvoiceStatusDocument, options);
      }
export function useCheckInvoiceStatusLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CheckInvoiceStatusQuery, CheckInvoiceStatusQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CheckInvoiceStatusQuery, CheckInvoiceStatusQueryVariables>(CheckInvoiceStatusDocument, options);
        }
export type CheckInvoiceStatusQueryHookResult = ReturnType<typeof useCheckInvoiceStatusQuery>;
export type CheckInvoiceStatusLazyQueryHookResult = ReturnType<typeof useCheckInvoiceStatusLazyQuery>;
export type CheckInvoiceStatusQueryResult = Apollo.QueryResult<CheckInvoiceStatusQuery, CheckInvoiceStatusQueryVariables>;
export const MemberPlanListDocument = gql`
    query MemberPlanList($filter: MemberPlanFilter, $cursorId: String, $take: Int, $skip: Int, $order: SortOrder, $sort: MemberPlanSort) {
  memberPlans(
    filter: $filter
    cursorId: $cursorId
    take: $take
    skip: $skip
    order: $order
    sort: $sort
  ) {
    nodes {
      ...FullMemberPlan
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}
    ${FullMemberPlanFragmentDoc}
${FullImageFragmentDoc}
${FullImageUrLsFragmentDoc}
${ImageUrLsFragmentDoc}
${SquareImageUrLsFragmentDoc}
${FullAvailablePaymentMethodFragmentDoc}
${FullPaymentMethodFragmentDoc}
${FullGoodieFragmentDoc}`;

/**
 * __useMemberPlanListQuery__
 *
 * To run a query within a React component, call `useMemberPlanListQuery` and pass it any options that fit your needs.
 * When your component renders, `useMemberPlanListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMemberPlanListQuery({
 *   variables: {
 *      filter: // value for 'filter'
 *      cursorId: // value for 'cursorId'
 *      take: // value for 'take'
 *      skip: // value for 'skip'
 *      order: // value for 'order'
 *      sort: // value for 'sort'
 *   },
 * });
 */
export function useMemberPlanListQuery(baseOptions?: Apollo.QueryHookOptions<MemberPlanListQuery, MemberPlanListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MemberPlanListQuery, MemberPlanListQueryVariables>(MemberPlanListDocument, options);
      }
export function useMemberPlanListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MemberPlanListQuery, MemberPlanListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MemberPlanListQuery, MemberPlanListQueryVariables>(MemberPlanListDocument, options);
        }
export type MemberPlanListQueryHookResult = ReturnType<typeof useMemberPlanListQuery>;
export type MemberPlanListLazyQueryHookResult = ReturnType<typeof useMemberPlanListLazyQuery>;
export type MemberPlanListQueryResult = Apollo.QueryResult<MemberPlanListQuery, MemberPlanListQueryVariables>;
export const RevenueDocument = gql`
    query Revenue($start: DateTime!, $end: DateTime) {
  revenue(start: $start, end: $end) {
    amount
    paidAt
    memberPlan
  }
}
    `;

/**
 * __useRevenueQuery__
 *
 * To run a query within a React component, call `useRevenueQuery` and pass it any options that fit your needs.
 * When your component renders, `useRevenueQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useRevenueQuery({
 *   variables: {
 *      start: // value for 'start'
 *      end: // value for 'end'
 *   },
 * });
 */
export function useRevenueQuery(baseOptions: Apollo.QueryHookOptions<RevenueQuery, RevenueQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<RevenueQuery, RevenueQueryVariables>(RevenueDocument, options);
      }
export function useRevenueLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<RevenueQuery, RevenueQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<RevenueQuery, RevenueQueryVariables>(RevenueDocument, options);
        }
export type RevenueQueryHookResult = ReturnType<typeof useRevenueQuery>;
export type RevenueLazyQueryHookResult = ReturnType<typeof useRevenueLazyQuery>;
export type RevenueQueryResult = Apollo.QueryResult<RevenueQuery, RevenueQueryVariables>;
export const NewSubscribersDocument = gql`
    query NewSubscribers($start: DateTime!, $end: DateTime) {
  newSubscribers(start: $start, end: $end) {
    monthlyAmount
    memberPlan
  }
}
    `;

/**
 * __useNewSubscribersQuery__
 *
 * To run a query within a React component, call `useNewSubscribersQuery` and pass it any options that fit your needs.
 * When your component renders, `useNewSubscribersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useNewSubscribersQuery({
 *   variables: {
 *      start: // value for 'start'
 *      end: // value for 'end'
 *   },
 * });
 */
export function useNewSubscribersQuery(baseOptions: Apollo.QueryHookOptions<NewSubscribersQuery, NewSubscribersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<NewSubscribersQuery, NewSubscribersQueryVariables>(NewSubscribersDocument, options);
      }
export function useNewSubscribersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<NewSubscribersQuery, NewSubscribersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<NewSubscribersQuery, NewSubscribersQueryVariables>(NewSubscribersDocument, options);
        }
export type NewSubscribersQueryHookResult = ReturnType<typeof useNewSubscribersQuery>;
export type NewSubscribersLazyQueryHookResult = ReturnType<typeof useNewSubscribersLazyQuery>;
export type NewSubscribersQueryResult = Apollo.QueryResult<NewSubscribersQuery, NewSubscribersQueryVariables>;
export const UpgradeSubscriptionInfoDocument = gql`
    query UpgradeSubscriptionInfo($memberPlanId: String!, $subscriptionId: String!, $discountCode: String) {
  upgradeUserSubscriptionInfo(
    memberPlanId: $memberPlanId
    subscriptionId: $subscriptionId
    discountCode: $discountCode
  ) {
    discountAmount
    discountPercent
    discountCodeValid
  }
}
    `;

/**
 * __useUpgradeSubscriptionInfoQuery__
 *
 * To run a query within a React component, call `useUpgradeSubscriptionInfoQuery` and pass it any options that fit your needs.
 * When your component renders, `useUpgradeSubscriptionInfoQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUpgradeSubscriptionInfoQuery({
 *   variables: {
 *      memberPlanId: // value for 'memberPlanId'
 *      subscriptionId: // value for 'subscriptionId'
 *      discountCode: // value for 'discountCode'
 *   },
 * });
 */
export function useUpgradeSubscriptionInfoQuery(baseOptions: Apollo.QueryHookOptions<UpgradeSubscriptionInfoQuery, UpgradeSubscriptionInfoQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UpgradeSubscriptionInfoQuery, UpgradeSubscriptionInfoQueryVariables>(UpgradeSubscriptionInfoDocument, options);
      }
export function useUpgradeSubscriptionInfoLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UpgradeSubscriptionInfoQuery, UpgradeSubscriptionInfoQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UpgradeSubscriptionInfoQuery, UpgradeSubscriptionInfoQueryVariables>(UpgradeSubscriptionInfoDocument, options);
        }
export type UpgradeSubscriptionInfoQueryHookResult = ReturnType<typeof useUpgradeSubscriptionInfoQuery>;
export type UpgradeSubscriptionInfoLazyQueryHookResult = ReturnType<typeof useUpgradeSubscriptionInfoLazyQuery>;
export type UpgradeSubscriptionInfoQueryResult = Apollo.QueryResult<UpgradeSubscriptionInfoQuery, UpgradeSubscriptionInfoQueryVariables>;
export const DiscountCodeListDocument = gql`
    query DiscountCodeList($filter: DiscountCodeFilter, $cursorId: String, $take: Int, $skip: Int, $order: SortOrder, $sort: DiscountCodesort) {
  discountCodes(
    filter: $filter
    cursorId: $cursorId
    take: $take
    skip: $skip
    order: $order
    sort: $sort
  ) {
    nodes {
      ...FullDiscountCode
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}
    ${FullDiscountCodeFragmentDoc}`;

/**
 * __useDiscountCodeListQuery__
 *
 * To run a query within a React component, call `useDiscountCodeListQuery` and pass it any options that fit your needs.
 * When your component renders, `useDiscountCodeListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useDiscountCodeListQuery({
 *   variables: {
 *      filter: // value for 'filter'
 *      cursorId: // value for 'cursorId'
 *      take: // value for 'take'
 *      skip: // value for 'skip'
 *      order: // value for 'order'
 *      sort: // value for 'sort'
 *   },
 * });
 */
export function useDiscountCodeListQuery(baseOptions?: Apollo.QueryHookOptions<DiscountCodeListQuery, DiscountCodeListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<DiscountCodeListQuery, DiscountCodeListQueryVariables>(DiscountCodeListDocument, options);
      }
export function useDiscountCodeListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<DiscountCodeListQuery, DiscountCodeListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<DiscountCodeListQuery, DiscountCodeListQueryVariables>(DiscountCodeListDocument, options);
        }
export type DiscountCodeListQueryHookResult = ReturnType<typeof useDiscountCodeListQuery>;
export type DiscountCodeListLazyQueryHookResult = ReturnType<typeof useDiscountCodeListLazyQuery>;
export type DiscountCodeListQueryResult = Apollo.QueryResult<DiscountCodeListQuery, DiscountCodeListQueryVariables>;