// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type FullAuditLogFragment = { __typename?: 'AuditLog', id: string, createdAt: string, mutation: string, action: Types.AuditLogAction, entity?: string | null, recordId?: string | null, actorType: Types.AuditLogActorType, userID?: string | null, userEmail?: string | null, tokenName?: string | null, sessionID?: string | null, impersonatedBy?: string | null, success: boolean, errorMessage?: string | null };

export type AuditLogListQueryVariables = Types.Exact<{
  filter?: Types.InputMaybe<Types.AuditLogFilter>;
  cursorId?: Types.InputMaybe<Types.Scalars['String']>;
  take?: Types.InputMaybe<Types.Scalars['Int']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  order?: Types.InputMaybe<Types.SortOrder>;
  sort?: Types.InputMaybe<Types.AuditLogSort>;
}>;


export type AuditLogListQuery = { __typename?: 'Query', auditLogs: { __typename?: 'PaginatedAuditLogs', totalCount: number, supported: boolean, nodes: Array<(
      { __typename?: 'AuditLog' }
      & FullAuditLogFragment
    )>, pageInfo: { __typename?: 'PageInfo', startCursor?: string | null, endCursor?: string | null, hasNextPage: boolean, hasPreviousPage: boolean } } };

export const FullAuditLogFragmentDoc = gql`
    fragment FullAuditLog on AuditLog {
  id
  createdAt
  mutation
  action
  entity
  recordId
  actorType
  userID
  userEmail
  tokenName
  sessionID
  impersonatedBy
  success
  errorMessage
}
    `;
export const AuditLogListDocument = gql`
    query AuditLogList($filter: AuditLogFilter, $cursorId: String, $take: Int, $skip: Int, $order: SortOrder, $sort: AuditLogSort) {
  auditLogs(
    filter: $filter
    cursorId: $cursorId
    take: $take
    skip: $skip
    order: $order
    sort: $sort
  ) {
    nodes {
      ...FullAuditLog
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalCount
    supported
  }
}
    ${FullAuditLogFragmentDoc}`;

/**
 * __useAuditLogListQuery__
 *
 * To run a query within a React component, call `useAuditLogListQuery` and pass it any options that fit your needs.
 * When your component renders, `useAuditLogListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useAuditLogListQuery({
 *   variables: {
 *      filter: // value for 'filter'
 *      cursorId: // value for 'cursorId'
 *      take: // value for 'take'
 *      skip: // value for 'skip'
 *      order: // value for 'order'
 *      sort: // value for 'sort'
 *   },
 * });
 */
export function useAuditLogListQuery(baseOptions?: Apollo.QueryHookOptions<AuditLogListQuery, AuditLogListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<AuditLogListQuery, AuditLogListQueryVariables>(AuditLogListDocument, options);
      }
export function useAuditLogListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<AuditLogListQuery, AuditLogListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<AuditLogListQuery, AuditLogListQueryVariables>(AuditLogListDocument, options);
        }
export type AuditLogListQueryHookResult = ReturnType<typeof useAuditLogListQuery>;
export type AuditLogListLazyQueryHookResult = ReturnType<typeof useAuditLogListLazyQuery>;
export type AuditLogListQueryResult = Apollo.QueryResult<AuditLogListQuery, AuditLogListQueryVariables>;