// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type ImportableEventRefFragment = { __typename?: 'EventFromSource', id: string, name: string, description?: RichtextJSONDocument | null, status: Types.EventStatus, location?: string | null, externalSourceId?: string | null, externalSourceName?: string | null, imageUrl?: string | null, startsAt: string, endsAt?: string | null };

export type ImportedEventListQueryVariables = Types.Exact<{
  filter?: Types.InputMaybe<Types.ImportedEventFilter>;
  order?: Types.InputMaybe<Types.Scalars['Int']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  take?: Types.InputMaybe<Types.Scalars['Int']>;
  sort?: Types.InputMaybe<Types.ImportedEventSort>;
}>;


export type ImportedEventListQuery = { __typename?: 'Query', importedEvents: { __typename?: 'PaginatedEventsFromSources', totalCount: number, nodes: Array<{ __typename?: 'EventFromSource', id: string, name: string, description?: RichtextJSONDocument | null, status: Types.EventStatus, location?: string | null, externalSourceId?: string | null, externalSourceName?: string | null, imageUrl?: string | null, startsAt: string, endsAt?: string | null }>, pageInfo: { __typename?: 'PageInfo', startCursor?: string | null, endCursor?: string | null, hasNextPage: boolean, hasPreviousPage: boolean } } };

export type ImportedEventQueryVariables = Types.Exact<{
  filter: Types.SingleEventFilter;
}>;


export type ImportedEventQuery = { __typename?: 'Query', importedEvent: { __typename?: 'EventFromSource', id: string, name: string, description?: RichtextJSONDocument | null, status: Types.EventStatus, location?: string | null, externalSourceId?: string | null, externalSourceName?: string | null, imageUrl?: string | null, startsAt: string, endsAt?: string | null } };

export type ImportedEventsIdsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type ImportedEventsIdsQuery = { __typename?: 'Query', importedEventsIds: Array<string> };

export type EventProvidersQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type EventProvidersQuery = { __typename?: 'Query', eventProviders: Array<string> };

export type ImportEventMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
  source: Types.Scalars['String'];
}>;


export type ImportEventMutation = { __typename?: 'Mutation', importEvent: string };

export const ImportableEventRefFragmentDoc = gql`
    fragment ImportableEventRef on EventFromSource {
  id
  name
  description
  status
  location
  externalSourceId
  externalSourceName
  imageUrl
  startsAt
  endsAt
}
    `;
export const ImportedEventListDocument = gql`
    query ImportedEventList($filter: ImportedEventFilter, $order: Int, $skip: Int, $take: Int, $sort: ImportedEventSort) {
  importedEvents(
    filter: $filter
    order: $order
    skip: $skip
    take: $take
    sort: $sort
  ) {
    nodes {
      ...ImportableEventRef
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}
    ${ImportableEventRefFragmentDoc}`;

/**
 * __useImportedEventListQuery__
 *
 * To run a query within a React component, call `useImportedEventListQuery` and pass it any options that fit your needs.
 * When your component renders, `useImportedEventListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useImportedEventListQuery({
 *   variables: {
 *      filter: // value for 'filter'
 *      order: // value for 'order'
 *      skip: // value for 'skip'
 *      take: // value for 'take'
 *      sort: // value for 'sort'
 *   },
 * });
 */
export function useImportedEventListQuery(baseOptions?: Apollo.QueryHookOptions<ImportedEventListQuery, ImportedEventListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ImportedEventListQuery, ImportedEventListQueryVariables>(ImportedEventListDocument, options);
      }
export function useImportedEventListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ImportedEventListQuery, ImportedEventListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ImportedEventListQuery, ImportedEventListQueryVariables>(ImportedEventListDocument, options);
        }
export type ImportedEventListQueryHookResult = ReturnType<typeof useImportedEventListQuery>;
export type ImportedEventListLazyQueryHookResult = ReturnType<typeof useImportedEventListLazyQuery>;
export type ImportedEventListQueryResult = Apollo.QueryResult<ImportedEventListQuery, ImportedEventListQueryVariables>;
export const ImportedEventDocument = gql`
    query ImportedEvent($filter: SingleEventFilter!) {
  importedEvent(filter: $filter) {
    ...ImportableEventRef
  }
}
    ${ImportableEventRefFragmentDoc}`;

/**
 * __useImportedEventQuery__
 *
 * To run a query within a React component, call `useImportedEventQuery` and pass it any options that fit your needs.
 * When your component renders, `useImportedEventQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useImportedEventQuery({
 *   variables: {
 *      filter: // value for 'filter'
 *   },
 * });
 */
export function useImportedEventQuery(baseOptions: Apollo.QueryHookOptions<ImportedEventQuery, ImportedEventQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ImportedEventQuery, ImportedEventQueryVariables>(ImportedEventDocument, options);
      }
export function useImportedEventLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ImportedEventQuery, ImportedEventQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ImportedEventQuery, ImportedEventQueryVariables>(ImportedEventDocument, options);
        }
export type ImportedEventQueryHookResult = ReturnType<typeof useImportedEventQuery>;
export type ImportedEventLazyQueryHookResult = ReturnType<typeof useImportedEventLazyQuery>;
export type ImportedEventQueryResult = Apollo.QueryResult<ImportedEventQuery, ImportedEventQueryVariables>;
export const ImportedEventsIdsDocument = gql`
    query ImportedEventsIds {
  importedEventsIds
}
    `;

/**
 * __useImportedEventsIdsQuery__
 *
 * To run a query within a React component, call `useImportedEventsIdsQuery` and pass it any options that fit your needs.
 * When your component renders, `useImportedEventsIdsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useImportedEventsIdsQuery({
 *   variables: {
 *   },
 * });
 */
export function useImportedEventsIdsQuery(baseOptions?: Apollo.QueryHookOptions<ImportedEventsIdsQuery, ImportedEventsIdsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ImportedEventsIdsQuery, ImportedEventsIdsQueryVariables>(ImportedEventsIdsDocument, options);
      }
export function useImportedEventsIdsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ImportedEventsIdsQuery, ImportedEventsIdsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ImportedEventsIdsQuery, ImportedEventsIdsQueryVariables>(ImportedEventsIdsDocument, options);
        }
export type ImportedEventsIdsQueryHookResult = ReturnType<typeof useImportedEventsIdsQuery>;
export type ImportedEventsIdsLazyQueryHookResult = ReturnType<typeof useImportedEventsIdsLazyQuery>;
export type ImportedEventsIdsQueryResult = Apollo.QueryResult<ImportedEventsIdsQuery, ImportedEventsIdsQueryVariables>;
export const EventProvidersDocument = gql`
    query EventProviders {
  eventProviders
}
    `;

/**
 * __useEventProvidersQuery__
 *
 * To run a query within a React component, call `useEventProvidersQuery` and pass it any options that fit your needs.
 * When your component renders, `useEventProvidersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useEventProvidersQuery({
 *   variables: {
 *   },
 * });
 */
export function useEventProvidersQuery(baseOptions?: Apollo.QueryHookOptions<EventProvidersQuery, EventProvidersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<EventProvidersQuery, EventProvidersQueryVariables>(EventProvidersDocument, options);
      }
export function useEventProvidersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<EventProvidersQuery, EventProvidersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<EventProvidersQuery, EventProvidersQueryVariables>(EventProvidersDocument, options);
        }
export type EventProvidersQueryHookResult = ReturnType<typeof useEventProvidersQuery>;
export type EventProvidersLazyQueryHookResult = ReturnType<typeof useEventProvidersLazyQuery>;
export type EventProvidersQueryResult = Apollo.QueryResult<EventProvidersQuery, EventProvidersQueryVariables>;
export const ImportEventDocument = gql`
    mutation ImportEvent($id: String!, $source: String!) {
  importEvent(id: $id, source: $source)
}
    `;
export type ImportEventMutationFn = Apollo.MutationFunction<ImportEventMutation, ImportEventMutationVariables>;

/**
 * __useImportEventMutation__
 *
 * To run a mutation, you first call `useImportEventMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useImportEventMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [importEventMutation, { data, loading, error }] = useImportEventMutation({
 *   variables: {
 *      id: // value for 'id'
 *      source: // value for 'source'
 *   },
 * });
 */
export function useImportEventMutation(baseOptions?: Apollo.MutationHookOptions<ImportEventMutation, ImportEventMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<ImportEventMutation, ImportEventMutationVariables>(ImportEventDocument, options);
      }
export type ImportEventMutationHookResult = ReturnType<typeof useImportEventMutation>;
export type ImportEventMutationResult = Apollo.MutationResult<ImportEventMutation>;
export type ImportEventMutationOptions = Apollo.BaseMutationOptions<ImportEventMutation, ImportEventMutationVariables>;