// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type FullMailSendJobFragment = { __typename?: 'MailSendJobModel', id: string, createdAt: string, modifiedAt: string, status: Types.MailSendJobState, audience: Types.MailSendAudience, totalCount: number, sentCount: number, failedCount: number, sendingCount: number, resumeCount: number, startedAt?: string | null, finishedAt?: string | null, heartbeatAt?: string | null, error?: string | null, mailTemplate?: { __typename?: 'MailLogTemplate', id: string, name: string } | null };

export type MailSendRecipientPreviewQueryVariables = Types.Exact<{
  audience: Types.MailAudienceInput;
}>;


export type MailSendRecipientPreviewQuery = { __typename?: 'Query', mailSendRecipientPreview: { __typename?: 'MailSendRecipientPreview', count: number, userCount: number, allowsSubscriptionTemplates: boolean } };

export type MailSendRecipientsQueryVariables = Types.Exact<{
  audience: Types.MailAudienceInput;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  take?: Types.InputMaybe<Types.Scalars['Int']>;
}>;


export type MailSendRecipientsQuery = { __typename?: 'Query', mailSendRecipients: { __typename?: 'PaginatedMailSendRecipient', totalCount: number, nodes: Array<{ __typename?: 'MailSendRecipientModel', id: string, userId: string, email: string, name: string, firstName?: string | null, subscriptionId?: string | null, memberPlanName?: string | null }>, pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean, hasPreviousPage: boolean } } };

export type MailSendPreviewQueryVariables = Types.Exact<{
  input: Types.MailSendPreviewInput;
}>;


export type MailSendPreviewQuery = { __typename?: 'Query', mailSendPreview: { __typename?: 'MailSendPreviewModel', subject: string, html: string, recipient?: { __typename?: 'MailSendRecipientModel', id: string, email: string, name: string, firstName?: string | null, memberPlanName?: string | null } | null } };

export type MailTemplateMissingPlaceholdersQueryVariables = Types.Exact<{
  templateId: Types.Scalars['String'];
  withSubscriptionData: Types.Scalars['Boolean'];
}>;


export type MailTemplateMissingPlaceholdersQuery = { __typename?: 'Query', mailTemplateMissingPlaceholders: Array<string> };

export type MailSendJobQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type MailSendJobQuery = { __typename?: 'Query', mailSendJob?: { __typename?: 'MailSendJobModel', id: string, createdAt: string, modifiedAt: string, status: Types.MailSendJobState, audience: Types.MailSendAudience, totalCount: number, sentCount: number, failedCount: number, sendingCount: number, resumeCount: number, startedAt?: string | null, finishedAt?: string | null, heartbeatAt?: string | null, error?: string | null, mailTemplate?: { __typename?: 'MailLogTemplate', id: string, name: string } | null } | null };

export type MailSendJobsQueryVariables = Types.Exact<{
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  take?: Types.InputMaybe<Types.Scalars['Int']>;
}>;


export type MailSendJobsQuery = { __typename?: 'Query', mailSendJobs: { __typename?: 'PaginatedMailSendJob', totalCount: number, nodes: Array<{ __typename?: 'MailSendJobModel', id: string, createdAt: string, modifiedAt: string, status: Types.MailSendJobState, audience: Types.MailSendAudience, totalCount: number, sentCount: number, failedCount: number, sendingCount: number, resumeCount: number, startedAt?: string | null, finishedAt?: string | null, heartbeatAt?: string | null, error?: string | null, mailTemplate?: { __typename?: 'MailLogTemplate', id: string, name: string } | null }>, pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean, hasPreviousPage: boolean, startCursor?: string | null, endCursor?: string | null } } };

export type MailSendJobRecipientsQueryVariables = Types.Exact<{
  jobId: Types.Scalars['String'];
  state?: Types.InputMaybe<Types.MailSendJobRecipientState>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  take?: Types.InputMaybe<Types.Scalars['Int']>;
}>;


export type MailSendJobRecipientsQuery = { __typename?: 'Query', mailSendJobRecipients: { __typename?: 'PaginatedMailSendJobRecipient', totalCount: number, nodes: Array<{ __typename?: 'MailSendJobRecipientModel', id: string, position: number, state: Types.MailSendJobRecipientState, attempts: number, error?: string | null, sentAt?: string | null, mailLogId?: string | null, memberPlanName?: string | null, user: { __typename?: 'MailLogRecipient', id: string, email: string, name: string, firstName?: string | null } }>, pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean, hasPreviousPage: boolean } } };

export type ResumeMailSendJobMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
  retryUnfinished?: Types.InputMaybe<Types.Scalars['Boolean']>;
}>;


export type ResumeMailSendJobMutation = { __typename?: 'Mutation', resumeMailSendJob: { __typename?: 'MailSendJobModel', id: string, createdAt: string, modifiedAt: string, status: Types.MailSendJobState, audience: Types.MailSendAudience, totalCount: number, sentCount: number, failedCount: number, sendingCount: number, resumeCount: number, startedAt?: string | null, finishedAt?: string | null, heartbeatAt?: string | null, error?: string | null, mailTemplate?: { __typename?: 'MailLogTemplate', id: string, name: string } | null } };

export type CancelMailSendJobMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type CancelMailSendJobMutation = { __typename?: 'Mutation', cancelMailSendJob: { __typename?: 'MailSendJobModel', id: string, createdAt: string, modifiedAt: string, status: Types.MailSendJobState, audience: Types.MailSendAudience, totalCount: number, sentCount: number, failedCount: number, sendingCount: number, resumeCount: number, startedAt?: string | null, finishedAt?: string | null, heartbeatAt?: string | null, error?: string | null, mailTemplate?: { __typename?: 'MailLogTemplate', id: string, name: string } | null } };

export type SendMailTemplateToUserMutationVariables = Types.Exact<{
  templateId: Types.Scalars['String'];
  userId: Types.Scalars['String'];
}>;


export type SendMailTemplateToUserMutation = { __typename?: 'Mutation', sendMailTemplateToUser: { __typename?: 'MailSendJobModel', id: string, createdAt: string, modifiedAt: string, status: Types.MailSendJobState, audience: Types.MailSendAudience, totalCount: number, sentCount: number, failedCount: number, sendingCount: number, resumeCount: number, startedAt?: string | null, finishedAt?: string | null, heartbeatAt?: string | null, error?: string | null, mailTemplate?: { __typename?: 'MailLogTemplate', id: string, name: string } | null } };

export type CreateMailSendJobMutationVariables = Types.Exact<{
  input: Types.MailSendJobInput;
}>;


export type CreateMailSendJobMutation = { __typename?: 'Mutation', createMailSendJob: { __typename?: 'MailSendJobModel', id: string, createdAt: string, modifiedAt: string, status: Types.MailSendJobState, audience: Types.MailSendAudience, totalCount: number, sentCount: number, failedCount: number, sendingCount: number, resumeCount: number, startedAt?: string | null, finishedAt?: string | null, heartbeatAt?: string | null, error?: string | null, mailTemplate?: { __typename?: 'MailLogTemplate', id: string, name: string } | null } };

export const FullMailSendJobFragmentDoc = gql`
    fragment FullMailSendJob on MailSendJobModel {
  id
  createdAt
  modifiedAt
  status
  audience
  totalCount
  sentCount
  failedCount
  sendingCount
  resumeCount
  startedAt
  finishedAt
  heartbeatAt
  error
  mailTemplate {
    id
    name
  }
}
    `;
export const MailSendRecipientPreviewDocument = gql`
    query MailSendRecipientPreview($audience: MailAudienceInput!) {
  mailSendRecipientPreview(audience: $audience) {
    count
    userCount
    allowsSubscriptionTemplates
  }
}
    `;

/**
 * __useMailSendRecipientPreviewQuery__
 *
 * To run a query within a React component, call `useMailSendRecipientPreviewQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailSendRecipientPreviewQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailSendRecipientPreviewQuery({
 *   variables: {
 *      audience: // value for 'audience'
 *   },
 * });
 */
export function useMailSendRecipientPreviewQuery(baseOptions: Apollo.QueryHookOptions<MailSendRecipientPreviewQuery, MailSendRecipientPreviewQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailSendRecipientPreviewQuery, MailSendRecipientPreviewQueryVariables>(MailSendRecipientPreviewDocument, options);
      }
export function useMailSendRecipientPreviewLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailSendRecipientPreviewQuery, MailSendRecipientPreviewQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailSendRecipientPreviewQuery, MailSendRecipientPreviewQueryVariables>(MailSendRecipientPreviewDocument, options);
        }
export type MailSendRecipientPreviewQueryHookResult = ReturnType<typeof useMailSendRecipientPreviewQuery>;
export type MailSendRecipientPreviewLazyQueryHookResult = ReturnType<typeof useMailSendRecipientPreviewLazyQuery>;
export type MailSendRecipientPreviewQueryResult = Apollo.QueryResult<MailSendRecipientPreviewQuery, MailSendRecipientPreviewQueryVariables>;
export const MailSendRecipientsDocument = gql`
    query MailSendRecipients($audience: MailAudienceInput!, $skip: Int, $take: Int) {
  mailSendRecipients(audience: $audience, skip: $skip, take: $take) {
    nodes {
      id
      userId
      email
      name
      firstName
      subscriptionId
      memberPlanName
    }
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
  }
}
    `;

/**
 * __useMailSendRecipientsQuery__
 *
 * To run a query within a React component, call `useMailSendRecipientsQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailSendRecipientsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailSendRecipientsQuery({
 *   variables: {
 *      audience: // value for 'audience'
 *      skip: // value for 'skip'
 *      take: // value for 'take'
 *   },
 * });
 */
export function useMailSendRecipientsQuery(baseOptions: Apollo.QueryHookOptions<MailSendRecipientsQuery, MailSendRecipientsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailSendRecipientsQuery, MailSendRecipientsQueryVariables>(MailSendRecipientsDocument, options);
      }
export function useMailSendRecipientsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailSendRecipientsQuery, MailSendRecipientsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailSendRecipientsQuery, MailSendRecipientsQueryVariables>(MailSendRecipientsDocument, options);
        }
export type MailSendRecipientsQueryHookResult = ReturnType<typeof useMailSendRecipientsQuery>;
export type MailSendRecipientsLazyQueryHookResult = ReturnType<typeof useMailSendRecipientsLazyQuery>;
export type MailSendRecipientsQueryResult = Apollo.QueryResult<MailSendRecipientsQuery, MailSendRecipientsQueryVariables>;
export const MailSendPreviewDocument = gql`
    query MailSendPreview($input: MailSendPreviewInput!) {
  mailSendPreview(input: $input) {
    subject
    html
    recipient {
      id
      email
      name
      firstName
      memberPlanName
    }
  }
}
    `;

/**
 * __useMailSendPreviewQuery__
 *
 * To run a query within a React component, call `useMailSendPreviewQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailSendPreviewQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailSendPreviewQuery({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useMailSendPreviewQuery(baseOptions: Apollo.QueryHookOptions<MailSendPreviewQuery, MailSendPreviewQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailSendPreviewQuery, MailSendPreviewQueryVariables>(MailSendPreviewDocument, options);
      }
export function useMailSendPreviewLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailSendPreviewQuery, MailSendPreviewQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailSendPreviewQuery, MailSendPreviewQueryVariables>(MailSendPreviewDocument, options);
        }
export type MailSendPreviewQueryHookResult = ReturnType<typeof useMailSendPreviewQuery>;
export type MailSendPreviewLazyQueryHookResult = ReturnType<typeof useMailSendPreviewLazyQuery>;
export type MailSendPreviewQueryResult = Apollo.QueryResult<MailSendPreviewQuery, MailSendPreviewQueryVariables>;
export const MailTemplateMissingPlaceholdersDocument = gql`
    query MailTemplateMissingPlaceholders($templateId: String!, $withSubscriptionData: Boolean!) {
  mailTemplateMissingPlaceholders(
    templateId: $templateId
    withSubscriptionData: $withSubscriptionData
  )
}
    `;

/**
 * __useMailTemplateMissingPlaceholdersQuery__
 *
 * To run a query within a React component, call `useMailTemplateMissingPlaceholdersQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailTemplateMissingPlaceholdersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailTemplateMissingPlaceholdersQuery({
 *   variables: {
 *      templateId: // value for 'templateId'
 *      withSubscriptionData: // value for 'withSubscriptionData'
 *   },
 * });
 */
export function useMailTemplateMissingPlaceholdersQuery(baseOptions: Apollo.QueryHookOptions<MailTemplateMissingPlaceholdersQuery, MailTemplateMissingPlaceholdersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailTemplateMissingPlaceholdersQuery, MailTemplateMissingPlaceholdersQueryVariables>(MailTemplateMissingPlaceholdersDocument, options);
      }
export function useMailTemplateMissingPlaceholdersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailTemplateMissingPlaceholdersQuery, MailTemplateMissingPlaceholdersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailTemplateMissingPlaceholdersQuery, MailTemplateMissingPlaceholdersQueryVariables>(MailTemplateMissingPlaceholdersDocument, options);
        }
export type MailTemplateMissingPlaceholdersQueryHookResult = ReturnType<typeof useMailTemplateMissingPlaceholdersQuery>;
export type MailTemplateMissingPlaceholdersLazyQueryHookResult = ReturnType<typeof useMailTemplateMissingPlaceholdersLazyQuery>;
export type MailTemplateMissingPlaceholdersQueryResult = Apollo.QueryResult<MailTemplateMissingPlaceholdersQuery, MailTemplateMissingPlaceholdersQueryVariables>;
export const MailSendJobDocument = gql`
    query MailSendJob($id: String!) {
  mailSendJob(id: $id) {
    ...FullMailSendJob
  }
}
    ${FullMailSendJobFragmentDoc}`;

/**
 * __useMailSendJobQuery__
 *
 * To run a query within a React component, call `useMailSendJobQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailSendJobQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailSendJobQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useMailSendJobQuery(baseOptions: Apollo.QueryHookOptions<MailSendJobQuery, MailSendJobQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailSendJobQuery, MailSendJobQueryVariables>(MailSendJobDocument, options);
      }
export function useMailSendJobLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailSendJobQuery, MailSendJobQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailSendJobQuery, MailSendJobQueryVariables>(MailSendJobDocument, options);
        }
export type MailSendJobQueryHookResult = ReturnType<typeof useMailSendJobQuery>;
export type MailSendJobLazyQueryHookResult = ReturnType<typeof useMailSendJobLazyQuery>;
export type MailSendJobQueryResult = Apollo.QueryResult<MailSendJobQuery, MailSendJobQueryVariables>;
export const MailSendJobsDocument = gql`
    query MailSendJobs($skip: Int, $take: Int) {
  mailSendJobs(skip: $skip, take: $take) {
    nodes {
      ...FullMailSendJob
    }
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
    ${FullMailSendJobFragmentDoc}`;

/**
 * __useMailSendJobsQuery__
 *
 * To run a query within a React component, call `useMailSendJobsQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailSendJobsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailSendJobsQuery({
 *   variables: {
 *      skip: // value for 'skip'
 *      take: // value for 'take'
 *   },
 * });
 */
export function useMailSendJobsQuery(baseOptions?: Apollo.QueryHookOptions<MailSendJobsQuery, MailSendJobsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailSendJobsQuery, MailSendJobsQueryVariables>(MailSendJobsDocument, options);
      }
export function useMailSendJobsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailSendJobsQuery, MailSendJobsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailSendJobsQuery, MailSendJobsQueryVariables>(MailSendJobsDocument, options);
        }
export type MailSendJobsQueryHookResult = ReturnType<typeof useMailSendJobsQuery>;
export type MailSendJobsLazyQueryHookResult = ReturnType<typeof useMailSendJobsLazyQuery>;
export type MailSendJobsQueryResult = Apollo.QueryResult<MailSendJobsQuery, MailSendJobsQueryVariables>;
export const MailSendJobRecipientsDocument = gql`
    query MailSendJobRecipients($jobId: String!, $state: MailSendJobRecipientState, $skip: Int, $take: Int) {
  mailSendJobRecipients(jobId: $jobId, state: $state, skip: $skip, take: $take) {
    nodes {
      id
      position
      state
      attempts
      error
      sentAt
      mailLogId
      memberPlanName
      user {
        id
        email
        name
        firstName
      }
    }
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
  }
}
    `;

/**
 * __useMailSendJobRecipientsQuery__
 *
 * To run a query within a React component, call `useMailSendJobRecipientsQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailSendJobRecipientsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailSendJobRecipientsQuery({
 *   variables: {
 *      jobId: // value for 'jobId'
 *      state: // value for 'state'
 *      skip: // value for 'skip'
 *      take: // value for 'take'
 *   },
 * });
 */
export function useMailSendJobRecipientsQuery(baseOptions: Apollo.QueryHookOptions<MailSendJobRecipientsQuery, MailSendJobRecipientsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailSendJobRecipientsQuery, MailSendJobRecipientsQueryVariables>(MailSendJobRecipientsDocument, options);
      }
export function useMailSendJobRecipientsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailSendJobRecipientsQuery, MailSendJobRecipientsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailSendJobRecipientsQuery, MailSendJobRecipientsQueryVariables>(MailSendJobRecipientsDocument, options);
        }
export type MailSendJobRecipientsQueryHookResult = ReturnType<typeof useMailSendJobRecipientsQuery>;
export type MailSendJobRecipientsLazyQueryHookResult = ReturnType<typeof useMailSendJobRecipientsLazyQuery>;
export type MailSendJobRecipientsQueryResult = Apollo.QueryResult<MailSendJobRecipientsQuery, MailSendJobRecipientsQueryVariables>;
export const ResumeMailSendJobDocument = gql`
    mutation ResumeMailSendJob($id: String!, $retryUnfinished: Boolean) {
  resumeMailSendJob(id: $id, retryUnfinished: $retryUnfinished) {
    ...FullMailSendJob
  }
}
    ${FullMailSendJobFragmentDoc}`;
export type ResumeMailSendJobMutationFn = Apollo.MutationFunction<ResumeMailSendJobMutation, ResumeMailSendJobMutationVariables>;

/**
 * __useResumeMailSendJobMutation__
 *
 * To run a mutation, you first call `useResumeMailSendJobMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useResumeMailSendJobMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [resumeMailSendJobMutation, { data, loading, error }] = useResumeMailSendJobMutation({
 *   variables: {
 *      id: // value for 'id'
 *      retryUnfinished: // value for 'retryUnfinished'
 *   },
 * });
 */
export function useResumeMailSendJobMutation(baseOptions?: Apollo.MutationHookOptions<ResumeMailSendJobMutation, ResumeMailSendJobMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<ResumeMailSendJobMutation, ResumeMailSendJobMutationVariables>(ResumeMailSendJobDocument, options);
      }
export type ResumeMailSendJobMutationHookResult = ReturnType<typeof useResumeMailSendJobMutation>;
export type ResumeMailSendJobMutationResult = Apollo.MutationResult<ResumeMailSendJobMutation>;
export type ResumeMailSendJobMutationOptions = Apollo.BaseMutationOptions<ResumeMailSendJobMutation, ResumeMailSendJobMutationVariables>;
export const CancelMailSendJobDocument = gql`
    mutation CancelMailSendJob($id: String!) {
  cancelMailSendJob(id: $id) {
    ...FullMailSendJob
  }
}
    ${FullMailSendJobFragmentDoc}`;
export type CancelMailSendJobMutationFn = Apollo.MutationFunction<CancelMailSendJobMutation, CancelMailSendJobMutationVariables>;

/**
 * __useCancelMailSendJobMutation__
 *
 * To run a mutation, you first call `useCancelMailSendJobMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCancelMailSendJobMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [cancelMailSendJobMutation, { data, loading, error }] = useCancelMailSendJobMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useCancelMailSendJobMutation(baseOptions?: Apollo.MutationHookOptions<CancelMailSendJobMutation, CancelMailSendJobMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CancelMailSendJobMutation, CancelMailSendJobMutationVariables>(CancelMailSendJobDocument, options);
      }
export type CancelMailSendJobMutationHookResult = ReturnType<typeof useCancelMailSendJobMutation>;
export type CancelMailSendJobMutationResult = Apollo.MutationResult<CancelMailSendJobMutation>;
export type CancelMailSendJobMutationOptions = Apollo.BaseMutationOptions<CancelMailSendJobMutation, CancelMailSendJobMutationVariables>;
export const SendMailTemplateToUserDocument = gql`
    mutation SendMailTemplateToUser($templateId: String!, $userId: String!) {
  sendMailTemplateToUser(templateId: $templateId, userId: $userId) {
    ...FullMailSendJob
  }
}
    ${FullMailSendJobFragmentDoc}`;
export type SendMailTemplateToUserMutationFn = Apollo.MutationFunction<SendMailTemplateToUserMutation, SendMailTemplateToUserMutationVariables>;

/**
 * __useSendMailTemplateToUserMutation__
 *
 * To run a mutation, you first call `useSendMailTemplateToUserMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSendMailTemplateToUserMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [sendMailTemplateToUserMutation, { data, loading, error }] = useSendMailTemplateToUserMutation({
 *   variables: {
 *      templateId: // value for 'templateId'
 *      userId: // value for 'userId'
 *   },
 * });
 */
export function useSendMailTemplateToUserMutation(baseOptions?: Apollo.MutationHookOptions<SendMailTemplateToUserMutation, SendMailTemplateToUserMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<SendMailTemplateToUserMutation, SendMailTemplateToUserMutationVariables>(SendMailTemplateToUserDocument, options);
      }
export type SendMailTemplateToUserMutationHookResult = ReturnType<typeof useSendMailTemplateToUserMutation>;
export type SendMailTemplateToUserMutationResult = Apollo.MutationResult<SendMailTemplateToUserMutation>;
export type SendMailTemplateToUserMutationOptions = Apollo.BaseMutationOptions<SendMailTemplateToUserMutation, SendMailTemplateToUserMutationVariables>;
export const CreateMailSendJobDocument = gql`
    mutation CreateMailSendJob($input: MailSendJobInput!) {
  createMailSendJob(input: $input) {
    ...FullMailSendJob
  }
}
    ${FullMailSendJobFragmentDoc}`;
export type CreateMailSendJobMutationFn = Apollo.MutationFunction<CreateMailSendJobMutation, CreateMailSendJobMutationVariables>;

/**
 * __useCreateMailSendJobMutation__
 *
 * To run a mutation, you first call `useCreateMailSendJobMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateMailSendJobMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createMailSendJobMutation, { data, loading, error }] = useCreateMailSendJobMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreateMailSendJobMutation(baseOptions?: Apollo.MutationHookOptions<CreateMailSendJobMutation, CreateMailSendJobMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateMailSendJobMutation, CreateMailSendJobMutationVariables>(CreateMailSendJobDocument, options);
      }
export type CreateMailSendJobMutationHookResult = ReturnType<typeof useCreateMailSendJobMutation>;
export type CreateMailSendJobMutationResult = Apollo.MutationResult<CreateMailSendJobMutation>;
export type CreateMailSendJobMutationOptions = Apollo.BaseMutationOptions<CreateMailSendJobMutation, CreateMailSendJobMutationVariables>;