// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type FullPaywallFragment = { __typename?: 'Paywall', id: string, createdAt: string, modifiedAt: string, name?: string | null, description?: RichtextJSONDocument | null, circumventDescription?: RichtextJSONDocument | null, upgradeDescription?: RichtextJSONDocument | null, upgradeCircumventDescription?: RichtextJSONDocument | null, active: boolean, anyMemberPlan: boolean, alternativeSubscribeUrl?: string | null, fadeout: boolean, hideContentAfter: number, memberPlans: Array<{ __typename?: 'MemberPlan', id: string, name: string }>, bypasses: Array<{ __typename?: 'PaywallBypass', id: string, token: string }> };

export type PaywallListQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type PaywallListQuery = { __typename?: 'Query', paywalls: Array<{ __typename?: 'Paywall', id: string, createdAt: string, modifiedAt: string, name?: string | null, description?: RichtextJSONDocument | null, circumventDescription?: RichtextJSONDocument | null, upgradeDescription?: RichtextJSONDocument | null, upgradeCircumventDescription?: RichtextJSONDocument | null, active: boolean, anyMemberPlan: boolean, alternativeSubscribeUrl?: string | null, fadeout: boolean, hideContentAfter: number, memberPlans: Array<{ __typename?: 'MemberPlan', id: string, name: string }>, bypasses: Array<{ __typename?: 'PaywallBypass', id: string, token: string }> }> };

export type PaywallQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type PaywallQuery = { __typename?: 'Query', paywall: { __typename?: 'Paywall', id: string, createdAt: string, modifiedAt: string, name?: string | null, description?: RichtextJSONDocument | null, circumventDescription?: RichtextJSONDocument | null, upgradeDescription?: RichtextJSONDocument | null, upgradeCircumventDescription?: RichtextJSONDocument | null, active: boolean, anyMemberPlan: boolean, alternativeSubscribeUrl?: string | null, fadeout: boolean, hideContentAfter: number, memberPlans: Array<{ __typename?: 'MemberPlan', id: string, name: string }>, bypasses: Array<{ __typename?: 'PaywallBypass', id: string, token: string }> } };

export type CreatePaywallMutationVariables = Types.Exact<{
  name?: Types.InputMaybe<Types.Scalars['String']>;
  description?: Types.InputMaybe<Types.Scalars['RichText']>;
  circumventDescription?: Types.InputMaybe<Types.Scalars['RichText']>;
  active: Types.Scalars['Boolean'];
  anyMemberPlan: Types.Scalars['Boolean'];
  memberPlanIds: Array<Types.Scalars['String']> | Types.Scalars['String'];
  bypassTokens: Array<Types.Scalars['String']> | Types.Scalars['String'];
  alternativeSubscribeUrl?: Types.InputMaybe<Types.Scalars['String']>;
  upgradeDescription?: Types.InputMaybe<Types.Scalars['RichText']>;
  upgradeCircumventDescription?: Types.InputMaybe<Types.Scalars['RichText']>;
  fadeout: Types.Scalars['Boolean'];
  hideContentAfter: Types.Scalars['Int'];
}>;


export type CreatePaywallMutation = { __typename?: 'Mutation', createPaywall: { __typename?: 'Paywall', id: string, createdAt: string, modifiedAt: string, name?: string | null, description?: RichtextJSONDocument | null, circumventDescription?: RichtextJSONDocument | null, upgradeDescription?: RichtextJSONDocument | null, upgradeCircumventDescription?: RichtextJSONDocument | null, active: boolean, anyMemberPlan: boolean, alternativeSubscribeUrl?: string | null, fadeout: boolean, hideContentAfter: number, memberPlans: Array<{ __typename?: 'MemberPlan', id: string, name: string }>, bypasses: Array<{ __typename?: 'PaywallBypass', id: string, token: string }> } };

export type UpdatePaywallMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
  name?: Types.InputMaybe<Types.Scalars['String']>;
  description?: Types.InputMaybe<Types.Scalars['RichText']>;
  circumventDescription?: Types.InputMaybe<Types.Scalars['RichText']>;
  upgradeDescription?: Types.InputMaybe<Types.Scalars['RichText']>;
  upgradeCircumventDescription?: Types.InputMaybe<Types.Scalars['RichText']>;
  active?: Types.InputMaybe<Types.Scalars['Boolean']>;
  anyMemberPlan?: Types.InputMaybe<Types.Scalars['Boolean']>;
  memberPlanIds?: Types.InputMaybe<Array<Types.Scalars['String']> | Types.Scalars['String']>;
  bypassTokens?: Types.InputMaybe<Array<Types.Scalars['String']> | Types.Scalars['String']>;
  alternativeSubscribeUrl?: Types.InputMaybe<Types.Scalars['String']>;
  fadeout?: Types.InputMaybe<Types.Scalars['Boolean']>;
  hideContentAfter?: Types.InputMaybe<Types.Scalars['Int']>;
}>;


export type UpdatePaywallMutation = { __typename?: 'Mutation', updatePaywall: { __typename?: 'Paywall', id: string, createdAt: string, modifiedAt: string, name?: string | null, description?: RichtextJSONDocument | null, circumventDescription?: RichtextJSONDocument | null, upgradeDescription?: RichtextJSONDocument | null, upgradeCircumventDescription?: RichtextJSONDocument | null, active: boolean, anyMemberPlan: boolean, alternativeSubscribeUrl?: string | null, fadeout: boolean, hideContentAfter: number, memberPlans: Array<{ __typename?: 'MemberPlan', id: string, name: string }>, bypasses: Array<{ __typename?: 'PaywallBypass', id: string, token: string }> } };

export type DeletePaywallMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type DeletePaywallMutation = { __typename?: 'Mutation', deletePaywall: { __typename?: 'Paywall', id: string, createdAt: string, modifiedAt: string, name?: string | null, description?: RichtextJSONDocument | null, circumventDescription?: RichtextJSONDocument | null, upgradeDescription?: RichtextJSONDocument | null, upgradeCircumventDescription?: RichtextJSONDocument | null, active: boolean, anyMemberPlan: boolean, alternativeSubscribeUrl?: string | null, fadeout: boolean, hideContentAfter: number, memberPlans: Array<{ __typename?: 'MemberPlan', id: string, name: string }>, bypasses: Array<{ __typename?: 'PaywallBypass', id: string, token: string }> } };

export const FullPaywallFragmentDoc = gql`
    fragment FullPaywall on Paywall {
  id
  createdAt
  modifiedAt
  name
  description
  circumventDescription
  upgradeDescription
  upgradeCircumventDescription
  active
  anyMemberPlan
  alternativeSubscribeUrl
  memberPlans {
    id
    name
  }
  bypasses {
    id
    token
  }
  fadeout
  hideContentAfter
}
    `;
export const PaywallListDocument = gql`
    query PaywallList {
  paywalls {
    ...FullPaywall
  }
}
    ${FullPaywallFragmentDoc}`;

/**
 * __usePaywallListQuery__
 *
 * To run a query within a React component, call `usePaywallListQuery` and pass it any options that fit your needs.
 * When your component renders, `usePaywallListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePaywallListQuery({
 *   variables: {
 *   },
 * });
 */
export function usePaywallListQuery(baseOptions?: Apollo.QueryHookOptions<PaywallListQuery, PaywallListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PaywallListQuery, PaywallListQueryVariables>(PaywallListDocument, options);
      }
export function usePaywallListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PaywallListQuery, PaywallListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PaywallListQuery, PaywallListQueryVariables>(PaywallListDocument, options);
        }
export type PaywallListQueryHookResult = ReturnType<typeof usePaywallListQuery>;
export type PaywallListLazyQueryHookResult = ReturnType<typeof usePaywallListLazyQuery>;
export type PaywallListQueryResult = Apollo.QueryResult<PaywallListQuery, PaywallListQueryVariables>;
export const PaywallDocument = gql`
    query Paywall($id: String!) {
  paywall(id: $id) {
    ...FullPaywall
  }
}
    ${FullPaywallFragmentDoc}`;

/**
 * __usePaywallQuery__
 *
 * To run a query within a React component, call `usePaywallQuery` and pass it any options that fit your needs.
 * When your component renders, `usePaywallQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePaywallQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function usePaywallQuery(baseOptions: Apollo.QueryHookOptions<PaywallQuery, PaywallQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PaywallQuery, PaywallQueryVariables>(PaywallDocument, options);
      }
export function usePaywallLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PaywallQuery, PaywallQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PaywallQuery, PaywallQueryVariables>(PaywallDocument, options);
        }
export type PaywallQueryHookResult = ReturnType<typeof usePaywallQuery>;
export type PaywallLazyQueryHookResult = ReturnType<typeof usePaywallLazyQuery>;
export type PaywallQueryResult = Apollo.QueryResult<PaywallQuery, PaywallQueryVariables>;
export const CreatePaywallDocument = gql`
    mutation CreatePaywall($name: String, $description: RichText, $circumventDescription: RichText, $active: Boolean!, $anyMemberPlan: Boolean!, $memberPlanIds: [String!]!, $bypassTokens: [String!]!, $alternativeSubscribeUrl: String, $upgradeDescription: RichText, $upgradeCircumventDescription: RichText, $fadeout: Boolean!, $hideContentAfter: Int!) {
  createPaywall(
    name: $name
    description: $description
    circumventDescription: $circumventDescription
    upgradeDescription: $upgradeDescription
    upgradeCircumventDescription: $upgradeCircumventDescription
    anyMemberPlan: $anyMemberPlan
    active: $active
    memberPlanIds: $memberPlanIds
    bypassTokens: $bypassTokens
    alternativeSubscribeUrl: $alternativeSubscribeUrl
    fadeout: $fadeout
    hideContentAfter: $hideContentAfter
  ) {
    ...FullPaywall
  }
}
    ${FullPaywallFragmentDoc}`;
export type CreatePaywallMutationFn = Apollo.MutationFunction<CreatePaywallMutation, CreatePaywallMutationVariables>;

/**
 * __useCreatePaywallMutation__
 *
 * To run a mutation, you first call `useCreatePaywallMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreatePaywallMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createPaywallMutation, { data, loading, error }] = useCreatePaywallMutation({
 *   variables: {
 *      name: // value for 'name'
 *      description: // value for 'description'
 *      circumventDescription: // value for 'circumventDescription'
 *      active: // value for 'active'
 *      anyMemberPlan: // value for 'anyMemberPlan'
 *      memberPlanIds: // value for 'memberPlanIds'
 *      bypassTokens: // value for 'bypassTokens'
 *      alternativeSubscribeUrl: // value for 'alternativeSubscribeUrl'
 *      upgradeDescription: // value for 'upgradeDescription'
 *      upgradeCircumventDescription: // value for 'upgradeCircumventDescription'
 *      fadeout: // value for 'fadeout'
 *      hideContentAfter: // value for 'hideContentAfter'
 *   },
 * });
 */
export function useCreatePaywallMutation(baseOptions?: Apollo.MutationHookOptions<CreatePaywallMutation, CreatePaywallMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreatePaywallMutation, CreatePaywallMutationVariables>(CreatePaywallDocument, options);
      }
export type CreatePaywallMutationHookResult = ReturnType<typeof useCreatePaywallMutation>;
export type CreatePaywallMutationResult = Apollo.MutationResult<CreatePaywallMutation>;
export type CreatePaywallMutationOptions = Apollo.BaseMutationOptions<CreatePaywallMutation, CreatePaywallMutationVariables>;
export const UpdatePaywallDocument = gql`
    mutation UpdatePaywall($id: String!, $name: String, $description: RichText, $circumventDescription: RichText, $upgradeDescription: RichText, $upgradeCircumventDescription: RichText, $active: Boolean, $anyMemberPlan: Boolean, $memberPlanIds: [String!], $bypassTokens: [String!], $alternativeSubscribeUrl: String, $fadeout: Boolean, $hideContentAfter: Int) {
  updatePaywall(
    id: $id
    name: $name
    description: $description
    circumventDescription: $circumventDescription
    upgradeDescription: $upgradeDescription
    upgradeCircumventDescription: $upgradeCircumventDescription
    anyMemberPlan: $anyMemberPlan
    active: $active
    memberPlanIds: $memberPlanIds
    bypassTokens: $bypassTokens
    alternativeSubscribeUrl: $alternativeSubscribeUrl
    fadeout: $fadeout
    hideContentAfter: $hideContentAfter
  ) {
    ...FullPaywall
  }
}
    ${FullPaywallFragmentDoc}`;
export type UpdatePaywallMutationFn = Apollo.MutationFunction<UpdatePaywallMutation, UpdatePaywallMutationVariables>;

/**
 * __useUpdatePaywallMutation__
 *
 * To run a mutation, you first call `useUpdatePaywallMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdatePaywallMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updatePaywallMutation, { data, loading, error }] = useUpdatePaywallMutation({
 *   variables: {
 *      id: // value for 'id'
 *      name: // value for 'name'
 *      description: // value for 'description'
 *      circumventDescription: // value for 'circumventDescription'
 *      upgradeDescription: // value for 'upgradeDescription'
 *      upgradeCircumventDescription: // value for 'upgradeCircumventDescription'
 *      active: // value for 'active'
 *      anyMemberPlan: // value for 'anyMemberPlan'
 *      memberPlanIds: // value for 'memberPlanIds'
 *      bypassTokens: // value for 'bypassTokens'
 *      alternativeSubscribeUrl: // value for 'alternativeSubscribeUrl'
 *      fadeout: // value for 'fadeout'
 *      hideContentAfter: // value for 'hideContentAfter'
 *   },
 * });
 */
export function useUpdatePaywallMutation(baseOptions?: Apollo.MutationHookOptions<UpdatePaywallMutation, UpdatePaywallMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdatePaywallMutation, UpdatePaywallMutationVariables>(UpdatePaywallDocument, options);
      }
export type UpdatePaywallMutationHookResult = ReturnType<typeof useUpdatePaywallMutation>;
export type UpdatePaywallMutationResult = Apollo.MutationResult<UpdatePaywallMutation>;
export type UpdatePaywallMutationOptions = Apollo.BaseMutationOptions<UpdatePaywallMutation, UpdatePaywallMutationVariables>;
export const DeletePaywallDocument = gql`
    mutation DeletePaywall($id: String!) {
  deletePaywall(id: $id) {
    ...FullPaywall
  }
}
    ${FullPaywallFragmentDoc}`;
export type DeletePaywallMutationFn = Apollo.MutationFunction<DeletePaywallMutation, DeletePaywallMutationVariables>;

/**
 * __useDeletePaywallMutation__
 *
 * To run a mutation, you first call `useDeletePaywallMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeletePaywallMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deletePaywallMutation, { data, loading, error }] = useDeletePaywallMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useDeletePaywallMutation(baseOptions?: Apollo.MutationHookOptions<DeletePaywallMutation, DeletePaywallMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<DeletePaywallMutation, DeletePaywallMutationVariables>(DeletePaywallDocument, options);
      }
export type DeletePaywallMutationHookResult = ReturnType<typeof useDeletePaywallMutation>;
export type DeletePaywallMutationResult = Apollo.MutationResult<DeletePaywallMutation>;
export type DeletePaywallMutationOptions = Apollo.BaseMutationOptions<DeletePaywallMutation, DeletePaywallMutationVariables>;