// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type SeoChecklistQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type SeoChecklistQuery = { __typename?: 'Query', seoChecklist: { __typename?: 'SeoChecklist', websiteUrl: string, sitemapUrl: string, robotsUrl: string, checks: Array<{ __typename?: 'SeoCheck', id: Types.SeoCheckId, kind: Types.SeoCheckKind, status: Types.SeoCheckStatus, detail?: string | null, url?: string | null }> } };


export const SeoChecklistDocument = gql`
    query SeoChecklist {
  seoChecklist {
    websiteUrl
    sitemapUrl
    robotsUrl
    checks {
      id
      kind
      status
      detail
      url
    }
  }
}
    `;

/**
 * __useSeoChecklistQuery__
 *
 * To run a query within a React component, call `useSeoChecklistQuery` and pass it any options that fit your needs.
 * When your component renders, `useSeoChecklistQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSeoChecklistQuery({
 *   variables: {
 *   },
 * });
 */
export function useSeoChecklistQuery(baseOptions?: Apollo.QueryHookOptions<SeoChecklistQuery, SeoChecklistQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<SeoChecklistQuery, SeoChecklistQueryVariables>(SeoChecklistDocument, options);
      }
export function useSeoChecklistLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SeoChecklistQuery, SeoChecklistQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<SeoChecklistQuery, SeoChecklistQueryVariables>(SeoChecklistDocument, options);
        }
export type SeoChecklistQueryHookResult = ReturnType<typeof useSeoChecklistQuery>;
export type SeoChecklistLazyQueryHookResult = ReturnType<typeof useSeoChecklistLazyQuery>;
export type SeoChecklistQueryResult = Apollo.QueryResult<SeoChecklistQuery, SeoChecklistQueryVariables>;