// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type PdfRendererSettingsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type PdfRendererSettingsQuery = { __typename?: 'Query', pdfRendererSettings: Array<{ __typename?: 'SettingPdfRenderer', cloudflare_accountId?: string | null, createdAt: string, gotenberg_url?: string | null, gotenberg_username?: string | null, id: string, lastLoadedAt: string, modifiedAt: string, name?: string | null, timeoutMs?: number | null, type: Types.PdfRendererType }> };

export type UpdatePdfRendererSettingMutationVariables = Types.Exact<{
  type?: Types.InputMaybe<Types.PdfRendererType>;
  cloudflare_accountId?: Types.InputMaybe<Types.Scalars['String']>;
  cloudflare_apiToken?: Types.InputMaybe<Types.Scalars['String']>;
  gotenberg_url?: Types.InputMaybe<Types.Scalars['String']>;
  gotenberg_username?: Types.InputMaybe<Types.Scalars['String']>;
  gotenberg_password?: Types.InputMaybe<Types.Scalars['String']>;
  id: Types.Scalars['String'];
  name?: Types.InputMaybe<Types.Scalars['String']>;
  timeoutMs?: Types.InputMaybe<Types.Scalars['Int']>;
}>;


export type UpdatePdfRendererSettingMutation = { __typename?: 'Mutation', updatePdfRendererSetting: { __typename?: 'SettingPdfRenderer', cloudflare_accountId?: string | null, createdAt: string, gotenberg_url?: string | null, gotenberg_username?: string | null, id: string, lastLoadedAt: string, modifiedAt: string, name?: string | null, timeoutMs?: number | null, type: Types.PdfRendererType } };

export type CreatePdfRendererSettingMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
  type: Types.PdfRendererType;
  name?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type CreatePdfRendererSettingMutation = { __typename?: 'Mutation', createPdfRendererSetting: { __typename?: 'SettingPdfRenderer', createdAt: string, id: string, lastLoadedAt: string, modifiedAt: string, name?: string | null, type: Types.PdfRendererType } };

export type DeletePdfRendererSettingMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type DeletePdfRendererSettingMutation = { __typename?: 'Mutation', deletePdfRendererSetting: { __typename?: 'SettingPdfRenderer', id: string } };


export const PdfRendererSettingsDocument = gql`
    query PdfRendererSettings {
  pdfRendererSettings {
    cloudflare_accountId
    createdAt
    gotenberg_url
    gotenberg_username
    id
    lastLoadedAt
    modifiedAt
    name
    timeoutMs
    type
  }
}
    `;

/**
 * __usePdfRendererSettingsQuery__
 *
 * To run a query within a React component, call `usePdfRendererSettingsQuery` and pass it any options that fit your needs.
 * When your component renders, `usePdfRendererSettingsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePdfRendererSettingsQuery({
 *   variables: {
 *   },
 * });
 */
export function usePdfRendererSettingsQuery(baseOptions?: Apollo.QueryHookOptions<PdfRendererSettingsQuery, PdfRendererSettingsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PdfRendererSettingsQuery, PdfRendererSettingsQueryVariables>(PdfRendererSettingsDocument, options);
      }
export function usePdfRendererSettingsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PdfRendererSettingsQuery, PdfRendererSettingsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PdfRendererSettingsQuery, PdfRendererSettingsQueryVariables>(PdfRendererSettingsDocument, options);
        }
export type PdfRendererSettingsQueryHookResult = ReturnType<typeof usePdfRendererSettingsQuery>;
export type PdfRendererSettingsLazyQueryHookResult = ReturnType<typeof usePdfRendererSettingsLazyQuery>;
export type PdfRendererSettingsQueryResult = Apollo.QueryResult<PdfRendererSettingsQuery, PdfRendererSettingsQueryVariables>;
export const UpdatePdfRendererSettingDocument = gql`
    mutation UpdatePdfRendererSetting($type: PdfRendererType, $cloudflare_accountId: String, $cloudflare_apiToken: String, $gotenberg_url: String, $gotenberg_username: String, $gotenberg_password: String, $id: String!, $name: String, $timeoutMs: Int) {
  updatePdfRendererSetting(
    type: $type
    cloudflare_accountId: $cloudflare_accountId
    cloudflare_apiToken: $cloudflare_apiToken
    gotenberg_url: $gotenberg_url
    gotenberg_username: $gotenberg_username
    gotenberg_password: $gotenberg_password
    id: $id
    name: $name
    timeoutMs: $timeoutMs
  ) {
    cloudflare_accountId
    createdAt
    gotenberg_url
    gotenberg_username
    id
    lastLoadedAt
    modifiedAt
    name
    timeoutMs
    type
  }
}
    `;
export type UpdatePdfRendererSettingMutationFn = Apollo.MutationFunction<UpdatePdfRendererSettingMutation, UpdatePdfRendererSettingMutationVariables>;

/**
 * __useUpdatePdfRendererSettingMutation__
 *
 * To run a mutation, you first call `useUpdatePdfRendererSettingMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdatePdfRendererSettingMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updatePdfRendererSettingMutation, { data, loading, error }] = useUpdatePdfRendererSettingMutation({
 *   variables: {
 *      type: // value for 'type'
 *      cloudflare_accountId: // value for 'cloudflare_accountId'
 *      cloudflare_apiToken: // value for 'cloudflare_apiToken'
 *      gotenberg_url: // value for 'gotenberg_url'
 *      gotenberg_username: // value for 'gotenberg_username'
 *      gotenberg_password: // value for 'gotenberg_password'
 *      id: // value for 'id'
 *      name: // value for 'name'
 *      timeoutMs: // value for 'timeoutMs'
 *   },
 * });
 */
export function useUpdatePdfRendererSettingMutation(baseOptions?: Apollo.MutationHookOptions<UpdatePdfRendererSettingMutation, UpdatePdfRendererSettingMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdatePdfRendererSettingMutation, UpdatePdfRendererSettingMutationVariables>(UpdatePdfRendererSettingDocument, options);
      }
export type UpdatePdfRendererSettingMutationHookResult = ReturnType<typeof useUpdatePdfRendererSettingMutation>;
export type UpdatePdfRendererSettingMutationResult = Apollo.MutationResult<UpdatePdfRendererSettingMutation>;
export type UpdatePdfRendererSettingMutationOptions = Apollo.BaseMutationOptions<UpdatePdfRendererSettingMutation, UpdatePdfRendererSettingMutationVariables>;
export const CreatePdfRendererSettingDocument = gql`
    mutation CreatePdfRendererSetting($id: String!, $type: PdfRendererType!, $name: String) {
  createPdfRendererSetting(id: $id, type: $type, name: $name) {
    createdAt
    id
    lastLoadedAt
    modifiedAt
    name
    type
  }
}
    `;
export type CreatePdfRendererSettingMutationFn = Apollo.MutationFunction<CreatePdfRendererSettingMutation, CreatePdfRendererSettingMutationVariables>;

/**
 * __useCreatePdfRendererSettingMutation__
 *
 * To run a mutation, you first call `useCreatePdfRendererSettingMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreatePdfRendererSettingMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createPdfRendererSettingMutation, { data, loading, error }] = useCreatePdfRendererSettingMutation({
 *   variables: {
 *      id: // value for 'id'
 *      type: // value for 'type'
 *      name: // value for 'name'
 *   },
 * });
 */
export function useCreatePdfRendererSettingMutation(baseOptions?: Apollo.MutationHookOptions<CreatePdfRendererSettingMutation, CreatePdfRendererSettingMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreatePdfRendererSettingMutation, CreatePdfRendererSettingMutationVariables>(CreatePdfRendererSettingDocument, options);
      }
export type CreatePdfRendererSettingMutationHookResult = ReturnType<typeof useCreatePdfRendererSettingMutation>;
export type CreatePdfRendererSettingMutationResult = Apollo.MutationResult<CreatePdfRendererSettingMutation>;
export type CreatePdfRendererSettingMutationOptions = Apollo.BaseMutationOptions<CreatePdfRendererSettingMutation, CreatePdfRendererSettingMutationVariables>;
export const DeletePdfRendererSettingDocument = gql`
    mutation DeletePdfRendererSetting($id: String!) {
  deletePdfRendererSetting(id: $id) {
    id
  }
}
    `;
export type DeletePdfRendererSettingMutationFn = Apollo.MutationFunction<DeletePdfRendererSettingMutation, DeletePdfRendererSettingMutationVariables>;

/**
 * __useDeletePdfRendererSettingMutation__
 *
 * To run a mutation, you first call `useDeletePdfRendererSettingMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeletePdfRendererSettingMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deletePdfRendererSettingMutation, { data, loading, error }] = useDeletePdfRendererSettingMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useDeletePdfRendererSettingMutation(baseOptions?: Apollo.MutationHookOptions<DeletePdfRendererSettingMutation, DeletePdfRendererSettingMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<DeletePdfRendererSettingMutation, DeletePdfRendererSettingMutationVariables>(DeletePdfRendererSettingDocument, options);
      }
export type DeletePdfRendererSettingMutationHookResult = ReturnType<typeof useDeletePdfRendererSettingMutation>;
export type DeletePdfRendererSettingMutationResult = Apollo.MutationResult<DeletePdfRendererSettingMutation>;
export type DeletePdfRendererSettingMutationOptions = Apollo.BaseMutationOptions<DeletePdfRendererSettingMutation, DeletePdfRendererSettingMutationVariables>;