// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type MailProviderSettingsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type MailProviderSettingsQuery = { __typename?: 'Query', mailProviderSettings: Array<{ __typename?: 'SettingMailProvider', createdAt: string, fromAddress?: string | null, id: string, lastLoadedAt: string, mailchimp_baseURL?: string | null, mailgun_baseDomain?: string | null, mailgun_mailDomain?: string | null, modifiedAt: string, name?: string | null, replyToAddress?: string | null, slack_webhookURL?: string | null, smtp_host?: string | null, smtp_port?: number | null, smtp_secure?: boolean | null, smtp_user?: string | null, type: Types.MailProviderType }> };

export type UpdateMailProviderSettingMutationVariables = Types.Exact<{
  apiKey?: Types.InputMaybe<Types.Scalars['String']>;
  fromAddress?: Types.InputMaybe<Types.Scalars['String']>;
  id: Types.Scalars['String'];
  mailchimp_baseURL?: Types.InputMaybe<Types.Scalars['String']>;
  mailgun_baseDomain?: Types.InputMaybe<Types.Scalars['String']>;
  mailgun_mailDomain?: Types.InputMaybe<Types.Scalars['String']>;
  name?: Types.InputMaybe<Types.Scalars['String']>;
  replyToAddress?: Types.InputMaybe<Types.Scalars['String']>;
  slack_webhookURL?: Types.InputMaybe<Types.Scalars['String']>;
  smtp_host?: Types.InputMaybe<Types.Scalars['String']>;
  smtp_port?: Types.InputMaybe<Types.Scalars['Int']>;
  smtp_secure?: Types.InputMaybe<Types.Scalars['Boolean']>;
  smtp_user?: Types.InputMaybe<Types.Scalars['String']>;
  webhookEndpointSecret?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type UpdateMailProviderSettingMutation = { __typename?: 'Mutation', updateMailProviderSetting: { __typename?: 'SettingMailProvider', createdAt: string, fromAddress?: string | null, id: string, lastLoadedAt: string, mailchimp_baseURL?: string | null, mailgun_baseDomain?: string | null, mailgun_mailDomain?: string | null, modifiedAt: string, name?: string | null, replyToAddress?: string | null, slack_webhookURL?: string | null, smtp_host?: string | null, smtp_port?: number | null, smtp_secure?: boolean | null, smtp_user?: string | null, type: Types.MailProviderType } };


export const MailProviderSettingsDocument = gql`
    query MailProviderSettings {
  mailProviderSettings {
    createdAt
    fromAddress
    id
    lastLoadedAt
    mailchimp_baseURL
    mailgun_baseDomain
    mailgun_mailDomain
    modifiedAt
    name
    replyToAddress
    slack_webhookURL
    smtp_host
    smtp_port
    smtp_secure
    smtp_user
    type
  }
}
    `;

/**
 * __useMailProviderSettingsQuery__
 *
 * To run a query within a React component, call `useMailProviderSettingsQuery` and pass it any options that fit your needs.
 * When your component renders, `useMailProviderSettingsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMailProviderSettingsQuery({
 *   variables: {
 *   },
 * });
 */
export function useMailProviderSettingsQuery(baseOptions?: Apollo.QueryHookOptions<MailProviderSettingsQuery, MailProviderSettingsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MailProviderSettingsQuery, MailProviderSettingsQueryVariables>(MailProviderSettingsDocument, options);
      }
export function useMailProviderSettingsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MailProviderSettingsQuery, MailProviderSettingsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MailProviderSettingsQuery, MailProviderSettingsQueryVariables>(MailProviderSettingsDocument, options);
        }
export type MailProviderSettingsQueryHookResult = ReturnType<typeof useMailProviderSettingsQuery>;
export type MailProviderSettingsLazyQueryHookResult = ReturnType<typeof useMailProviderSettingsLazyQuery>;
export type MailProviderSettingsQueryResult = Apollo.QueryResult<MailProviderSettingsQuery, MailProviderSettingsQueryVariables>;
export const UpdateMailProviderSettingDocument = gql`
    mutation UpdateMailProviderSetting($apiKey: String, $fromAddress: String, $id: String!, $mailchimp_baseURL: String, $mailgun_baseDomain: String, $mailgun_mailDomain: String, $name: String, $replyToAddress: String, $slack_webhookURL: String, $smtp_host: String, $smtp_port: Int, $smtp_secure: Boolean, $smtp_user: String, $webhookEndpointSecret: String) {
  updateMailProviderSetting(
    apiKey: $apiKey
    fromAddress: $fromAddress
    id: $id
    mailchimp_baseURL: $mailchimp_baseURL
    mailgun_baseDomain: $mailgun_baseDomain
    mailgun_mailDomain: $mailgun_mailDomain
    name: $name
    replyToAddress: $replyToAddress
    slack_webhookURL: $slack_webhookURL
    smtp_host: $smtp_host
    smtp_port: $smtp_port
    smtp_secure: $smtp_secure
    smtp_user: $smtp_user
    webhookEndpointSecret: $webhookEndpointSecret
  ) {
    createdAt
    fromAddress
    id
    lastLoadedAt
    mailchimp_baseURL
    mailgun_baseDomain
    mailgun_mailDomain
    modifiedAt
    name
    replyToAddress
    slack_webhookURL
    smtp_host
    smtp_port
    smtp_secure
    smtp_user
    type
  }
}
    `;
export type UpdateMailProviderSettingMutationFn = Apollo.MutationFunction<UpdateMailProviderSettingMutation, UpdateMailProviderSettingMutationVariables>;

/**
 * __useUpdateMailProviderSettingMutation__
 *
 * To run a mutation, you first call `useUpdateMailProviderSettingMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateMailProviderSettingMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateMailProviderSettingMutation, { data, loading, error }] = useUpdateMailProviderSettingMutation({
 *   variables: {
 *      apiKey: // value for 'apiKey'
 *      fromAddress: // value for 'fromAddress'
 *      id: // value for 'id'
 *      mailchimp_baseURL: // value for 'mailchimp_baseURL'
 *      mailgun_baseDomain: // value for 'mailgun_baseDomain'
 *      mailgun_mailDomain: // value for 'mailgun_mailDomain'
 *      name: // value for 'name'
 *      replyToAddress: // value for 'replyToAddress'
 *      slack_webhookURL: // value for 'slack_webhookURL'
 *      smtp_host: // value for 'smtp_host'
 *      smtp_port: // value for 'smtp_port'
 *      smtp_secure: // value for 'smtp_secure'
 *      smtp_user: // value for 'smtp_user'
 *      webhookEndpointSecret: // value for 'webhookEndpointSecret'
 *   },
 * });
 */
export function useUpdateMailProviderSettingMutation(baseOptions?: Apollo.MutationHookOptions<UpdateMailProviderSettingMutation, UpdateMailProviderSettingMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdateMailProviderSettingMutation, UpdateMailProviderSettingMutationVariables>(UpdateMailProviderSettingDocument, options);
      }
export type UpdateMailProviderSettingMutationHookResult = ReturnType<typeof useUpdateMailProviderSettingMutation>;
export type UpdateMailProviderSettingMutationResult = Apollo.MutationResult<UpdateMailProviderSettingMutation>;
export type UpdateMailProviderSettingMutationOptions = Apollo.BaseMutationOptions<UpdateMailProviderSettingMutation, UpdateMailProviderSettingMutationVariables>;