// THIS FILE IS AUTOGENERATED
import * as Types from '../graphql';

import {RichtextJSONDocument} from '@wepublish/richtext';
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
import * as ApolloReactHooks from '@apollo/client/react';
const defaultOptions = {} as const;
export type TrackingPixelSettingsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type TrackingPixelSettingsQuery = { __typename?: 'Query', trackingPixelSettings: Array<{ __typename?: 'SettingTrackingPixelProvider', deletedAt?: string | null, createdAt: string, id: string, lastLoadedAt: string, modifiedAt: string, name?: string | null, prolitteris_memberNr?: string | null, prolitteris_onlyPaidContentAccess?: boolean | null, prolitteris_publisherInternalKeyDomain?: string | null, prolitteris_usePublisherInternalKey?: boolean | null, prolitteris_username?: string | null, type: Types.TrackingPixelProviderType }> };

export type UpdateTrackingPixelSettingMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
  name?: Types.InputMaybe<Types.Scalars['String']>;
  prolitteris_memberNr?: Types.InputMaybe<Types.Scalars['String']>;
  prolitteris_onlyPaidContentAccess?: Types.InputMaybe<Types.Scalars['Boolean']>;
  prolitteris_password?: Types.InputMaybe<Types.Scalars['String']>;
  prolitteris_publisherInternalKeyDomain?: Types.InputMaybe<Types.Scalars['String']>;
  prolitteris_usePublisherInternalKey?: Types.InputMaybe<Types.Scalars['Boolean']>;
  prolitteris_username?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type UpdateTrackingPixelSettingMutation = { __typename?: 'Mutation', updateTrackingPixelSetting: { __typename?: 'SettingTrackingPixelProvider', createdAt: string, id: string, lastLoadedAt: string, modifiedAt: string, name?: string | null, prolitteris_memberNr?: string | null, prolitteris_onlyPaidContentAccess?: boolean | null, prolitteris_publisherInternalKeyDomain?: string | null, prolitteris_usePublisherInternalKey?: boolean | null, prolitteris_username?: string | null, type: Types.TrackingPixelProviderType } };

export type CreateTrackingPixelSettingMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
  type: Types.TrackingPixelProviderType;
  name?: Types.InputMaybe<Types.Scalars['String']>;
}>;


export type CreateTrackingPixelSettingMutation = { __typename?: 'Mutation', createTrackingPixelSetting: { __typename?: 'SettingTrackingPixelProvider', createdAt: string, deletedAt?: string | null, id: string, lastLoadedAt: string, modifiedAt: string, name?: string | null, type: Types.TrackingPixelProviderType } };

export type DeleteTrackingPixelSettingMutationVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type DeleteTrackingPixelSettingMutation = { __typename?: 'Mutation', deleteTrackingPixelSetting: { __typename?: 'SettingTrackingPixelProvider', deletedAt?: string | null, id: string } };


export const TrackingPixelSettingsDocument = gql`
    query TrackingPixelSettings {
  trackingPixelSettings {
    deletedAt
    createdAt
    id
    lastLoadedAt
    modifiedAt
    name
    prolitteris_memberNr
    prolitteris_onlyPaidContentAccess
    prolitteris_publisherInternalKeyDomain
    prolitteris_usePublisherInternalKey
    prolitteris_username
    type
  }
}
    `;

/**
 * __useTrackingPixelSettingsQuery__
 *
 * To run a query within a React component, call `useTrackingPixelSettingsQuery` and pass it any options that fit your needs.
 * When your component renders, `useTrackingPixelSettingsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useTrackingPixelSettingsQuery({
 *   variables: {
 *   },
 * });
 */
export function useTrackingPixelSettingsQuery(baseOptions?: ApolloReactHooks.QueryHookOptions<TrackingPixelSettingsQuery, TrackingPixelSettingsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return ApolloReactHooks.useQuery<TrackingPixelSettingsQuery, TrackingPixelSettingsQueryVariables>(TrackingPixelSettingsDocument, options);
      }
export function useTrackingPixelSettingsLazyQuery(baseOptions?: ApolloReactHooks.LazyQueryHookOptions<TrackingPixelSettingsQuery, TrackingPixelSettingsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return ApolloReactHooks.useLazyQuery<TrackingPixelSettingsQuery, TrackingPixelSettingsQueryVariables>(TrackingPixelSettingsDocument, options);
        }
export type TrackingPixelSettingsQueryHookResult = ReturnType<typeof useTrackingPixelSettingsQuery>;
export type TrackingPixelSettingsLazyQueryHookResult = ReturnType<typeof useTrackingPixelSettingsLazyQuery>;
export type TrackingPixelSettingsQueryResult = Apollo.QueryResult<TrackingPixelSettingsQuery, TrackingPixelSettingsQueryVariables>;
export const UpdateTrackingPixelSettingDocument = gql`
    mutation UpdateTrackingPixelSetting($id: String!, $name: String, $prolitteris_memberNr: String, $prolitteris_onlyPaidContentAccess: Boolean, $prolitteris_password: String, $prolitteris_publisherInternalKeyDomain: String, $prolitteris_usePublisherInternalKey: Boolean, $prolitteris_username: String) {
  updateTrackingPixelSetting(
    id: $id
    name: $name
    prolitteris_memberNr: $prolitteris_memberNr
    prolitteris_onlyPaidContentAccess: $prolitteris_onlyPaidContentAccess
    prolitteris_password: $prolitteris_password
    prolitteris_publisherInternalKeyDomain: $prolitteris_publisherInternalKeyDomain
    prolitteris_usePublisherInternalKey: $prolitteris_usePublisherInternalKey
    prolitteris_username: $prolitteris_username
  ) {
    createdAt
    id
    lastLoadedAt
    modifiedAt
    name
    prolitteris_memberNr
    prolitteris_onlyPaidContentAccess
    prolitteris_publisherInternalKeyDomain
    prolitteris_usePublisherInternalKey
    prolitteris_username
    type
  }
}
    `;
export type UpdateTrackingPixelSettingMutationFn = Apollo.MutationFunction<UpdateTrackingPixelSettingMutation, UpdateTrackingPixelSettingMutationVariables>;

/**
 * __useUpdateTrackingPixelSettingMutation__
 *
 * To run a mutation, you first call `useUpdateTrackingPixelSettingMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateTrackingPixelSettingMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateTrackingPixelSettingMutation, { data, loading, error }] = useUpdateTrackingPixelSettingMutation({
 *   variables: {
 *      id: // value for 'id'
 *      name: // value for 'name'
 *      prolitteris_memberNr: // value for 'prolitteris_memberNr'
 *      prolitteris_onlyPaidContentAccess: // value for 'prolitteris_onlyPaidContentAccess'
 *      prolitteris_password: // value for 'prolitteris_password'
 *      prolitteris_publisherInternalKeyDomain: // value for 'prolitteris_publisherInternalKeyDomain'
 *      prolitteris_usePublisherInternalKey: // value for 'prolitteris_usePublisherInternalKey'
 *      prolitteris_username: // value for 'prolitteris_username'
 *   },
 * });
 */
export function useUpdateTrackingPixelSettingMutation(baseOptions?: ApolloReactHooks.MutationHookOptions<UpdateTrackingPixelSettingMutation, UpdateTrackingPixelSettingMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return ApolloReactHooks.useMutation<UpdateTrackingPixelSettingMutation, UpdateTrackingPixelSettingMutationVariables>(UpdateTrackingPixelSettingDocument, options);
      }
export type UpdateTrackingPixelSettingMutationHookResult = ReturnType<typeof useUpdateTrackingPixelSettingMutation>;
export type UpdateTrackingPixelSettingMutationResult = Apollo.MutationResult<UpdateTrackingPixelSettingMutation>;
export type UpdateTrackingPixelSettingMutationOptions = Apollo.BaseMutationOptions<UpdateTrackingPixelSettingMutation, UpdateTrackingPixelSettingMutationVariables>;
export const CreateTrackingPixelSettingDocument = gql`
    mutation CreateTrackingPixelSetting($id: String!, $type: TrackingPixelProviderType!, $name: String) {
  createTrackingPixelSetting(id: $id, type: $type, name: $name) {
    createdAt
    deletedAt
    id
    lastLoadedAt
    modifiedAt
    name
    type
  }
}
    `;
export type CreateTrackingPixelSettingMutationFn = Apollo.MutationFunction<CreateTrackingPixelSettingMutation, CreateTrackingPixelSettingMutationVariables>;

/**
 * __useCreateTrackingPixelSettingMutation__
 *
 * To run a mutation, you first call `useCreateTrackingPixelSettingMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateTrackingPixelSettingMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createTrackingPixelSettingMutation, { data, loading, error }] = useCreateTrackingPixelSettingMutation({
 *   variables: {
 *      id: // value for 'id'
 *      type: // value for 'type'
 *      name: // value for 'name'
 *   },
 * });
 */
export function useCreateTrackingPixelSettingMutation(baseOptions?: ApolloReactHooks.MutationHookOptions<CreateTrackingPixelSettingMutation, CreateTrackingPixelSettingMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return ApolloReactHooks.useMutation<CreateTrackingPixelSettingMutation, CreateTrackingPixelSettingMutationVariables>(CreateTrackingPixelSettingDocument, options);
      }
export type CreateTrackingPixelSettingMutationHookResult = ReturnType<typeof useCreateTrackingPixelSettingMutation>;
export type CreateTrackingPixelSettingMutationResult = Apollo.MutationResult<CreateTrackingPixelSettingMutation>;
export type CreateTrackingPixelSettingMutationOptions = Apollo.BaseMutationOptions<CreateTrackingPixelSettingMutation, CreateTrackingPixelSettingMutationVariables>;
export const DeleteTrackingPixelSettingDocument = gql`
    mutation DeleteTrackingPixelSetting($id: String!) {
  deleteTrackingPixelSetting(id: $id) {
    deletedAt
    id
  }
}
    `;
export type DeleteTrackingPixelSettingMutationFn = Apollo.MutationFunction<DeleteTrackingPixelSettingMutation, DeleteTrackingPixelSettingMutationVariables>;

/**
 * __useDeleteTrackingPixelSettingMutation__
 *
 * To run a mutation, you first call `useDeleteTrackingPixelSettingMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteTrackingPixelSettingMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteTrackingPixelSettingMutation, { data, loading, error }] = useDeleteTrackingPixelSettingMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useDeleteTrackingPixelSettingMutation(baseOptions?: ApolloReactHooks.MutationHookOptions<DeleteTrackingPixelSettingMutation, DeleteTrackingPixelSettingMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return ApolloReactHooks.useMutation<DeleteTrackingPixelSettingMutation, DeleteTrackingPixelSettingMutationVariables>(DeleteTrackingPixelSettingDocument, options);
      }
export type DeleteTrackingPixelSettingMutationHookResult = ReturnType<typeof useDeleteTrackingPixelSettingMutation>;
export type DeleteTrackingPixelSettingMutationResult = Apollo.MutationResult<DeleteTrackingPixelSettingMutation>;
export type DeleteTrackingPixelSettingMutationOptions = Apollo.BaseMutationOptions<DeleteTrackingPixelSettingMutation, DeleteTrackingPixelSettingMutationVariables>;