query SettingsIntegrationsChallenge {
  challengeProviderSettings {
    createdAt
    id
    lastLoadedAt
    modifiedAt
    name
    type
  }
}

mutation UpdateSettingsIntegrationsChallenge(
  $id: String!
  $type: ChallengeProviderType
  $name: String
  $secret: String
  $siteKey: String
) {
  updateChallengeProviderSetting(
    id: $id
    type: $type
    name: $name
    secret: $secret
    siteKey: $siteKey
  ) {
    createdAt
    id
    lastLoadedAt
    modifiedAt
    name
    type
  }
}

mutation CreateSettingsIntegrationsChallenge(
  $id: String!
  $type: ChallengeProviderType!
  $name: String
) {
  createChallengeProviderSetting(id: $id, type: $type, name: $name) {
    id
    type
    name
  }
}
