query SubscriptionFlows($defaultFlowOnly: Boolean!, $memberPlanId: String) {
  subscriptionFlows(
    defaultFlowOnly: $defaultFlowOnly
    memberPlanId: $memberPlanId
  ) {
    ...SubscriptionFlow
  }
}

mutation CreateSubscriptionFlow(
  $memberPlanId: String!
  $paymentMethodIds: [String!]!
  $periodicities: [PaymentPeriodicity!]!
  $autoRenewal: [Boolean!]!
) {
  createSubscriptionFlow(
    memberPlanId: $memberPlanId
    paymentMethodIds: $paymentMethodIds
    periodicities: $periodicities
    autoRenewal: $autoRenewal
  ) {
    ...SubscriptionFlow
  }
}

mutation UpdateSubscriptionFlow(
  $id: String!
  $paymentMethodIds: [String!]!
  $periodicities: [PaymentPeriodicity!]!
  $autoRenewal: [Boolean!]!
) {
  updateSubscriptionFlow(
    id: $id
    paymentMethodIds: $paymentMethodIds
    periodicities: $periodicities
    autoRenewal: $autoRenewal
  ) {
    ...SubscriptionFlow
  }
}

mutation DeleteSubscriptionFlow($id: String!) {
  deleteSubscriptionFlow(id: $id) {
    ...SubscriptionFlow
  }
}

mutation CreateSubscriptionInterval(
  $subscriptionFlowId: String!
  $daysAwayFromEnding: Int
  $mailTemplateId: String
  $channels: [MessageChannel!]
  $event: SubscriptionEvent!
) {
  createSubscriptionInterval(
    subscriptionFlowId: $subscriptionFlowId
    daysAwayFromEnding: $daysAwayFromEnding
    mailTemplateId: $mailTemplateId
    channels: $channels
    event: $event
  ) {
    ...SubscriptionFlow
  }
}

mutation UpdateSubscriptionInterval(
  $id: String!
  $daysAwayFromEnding: Int
  $mailTemplateId: String
  $channels: [MessageChannel!]
  $addressPosition: LetterAddressPosition
  $deliveryProduct: LetterDeliveryProduct
  $printMode: LetterPrintMode
  $printSpectrum: LetterPrintSpectrum
  $qrBill: LetterQrBill
) {
  updateSubscriptionInterval(
    id: $id
    daysAwayFromEnding: $daysAwayFromEnding
    mailTemplateId: $mailTemplateId
    channels: $channels
    addressPosition: $addressPosition
    deliveryProduct: $deliveryProduct
    printMode: $printMode
    printSpectrum: $printSpectrum
    qrBill: $qrBill
  ) {
    ...SubscriptionFlow
  }
}

mutation DeleteSubscriptionInterval($id: String!) {
  deleteSubscriptionInterval(id: $id) {
    ...SubscriptionFlow
  }
}

query ListPaymentMethods {
  paymentMethods {
    ...FullPaymentMethod
  }
}

fragment SubscriptionFlow on SubscriptionFlowModel {
  id
  default
  memberPlan {
    ...MemberPlanRef
  }
  autoRenewal
  paymentMethods {
    ...FullPaymentMethod
  }
  periodicities
  intervals {
    ...SubscriptionInterval
  }
  numberOfSubscriptions
}

fragment SubscriptionInterval on SubscriptionInterval {
  id
  daysAwayFromEnding
  event
  mailTemplate {
    ...MailTemplateRef
  }
  channels
  addressPosition
  deliveryProduct
  printMode
  printSpectrum
  qrBill
}

fragment MailTemplateRef on MailTemplateRef {
  id
  name
}

fragment MemberPlanRef on MemberPlan {
  id
  name
  productType
  amountPerMonthMin
  amountPerMonthMax
  availablePaymentMethods {
    ...FullAvailablePaymentMethod
  }
  currency
  extendable
  slug
}

fragment FullAvailablePaymentMethod on AvailablePaymentMethod {
  paymentMethods {
    ...FullPaymentMethod
  }
  paymentPeriodicities
  forceAutoRenewal
}
