/**
 * Writes the `libs/{editor,website}/api/src/index.ts` barrels, run from
 * codegen's `afterAllFileWrite` hook (see codegen.yml).
 *
 * Why this is generated rather than hand-written: client-preset only emits the
 * schema types that operations actually select, but a lot of app code imports
 * the schema's own types (`Tag`, `MemberPlan`, `Event`, ...) as its domain
 * model. Those come from the separate `schema-types.ts` output, and the two
 * files overlap on every enum/input an operation happens to use — so
 * `export *` from both is ambiguous (TS2308). client-preset does not forward
 * `importSchemaTypesFrom`, which would otherwise let the operations file
 * import them instead of re-declaring them.
 *
 * So the barrel re-exports `gql/graphql` wholesale and then adds, by name,
 * only those schema types the operations file does not already export.
 * Recomputing that set on every codegen run keeps it correct as the schema
 * changes, instead of leaving a hand-maintained list to drift.
 */
const { readFileSync, writeFileSync } = require('node:fs');

const LIBS = [
  { name: 'editor', tail: "export * from './lib/setup';" },
  { name: 'website', tail: "export * from './lib/client';" },
];

const exported = (src, kinds) =>
  new Set(
    [...src.matchAll(new RegExp(`^export (?:${kinds}) (\\w+)`, 'gm'))].map(
      m => m[1]
    )
  );

for (const { name, tail } of LIBS) {
  const base = `libs/${name}/api/src`;
  const schema = readFileSync(`${base}/lib/schema-types.ts`, 'utf-8');
  const gql = readFileSync(`${base}/lib/gql/graphql.ts`, 'utf-8');

  const fromGql = exported(gql, 'type|enum|const|interface');
  const types = [...exported(schema, 'type|interface')]
    .filter(n => !fromGql.has(n))
    .sort();
  const enums = [...exported(schema, 'enum')]
    .filter(n => !fromGql.has(n))
    .sort();

  const blocks = [];
  if (types.length) {
    blocks.push(
      `export type {\n  ${types.join(',\n  ')},\n} from './lib/schema-types';`
    );
  }
  if (enums.length) {
    // Enum members are used as runtime values, so these are value exports.
    blocks.push(
      `export {\n  ${enums.join(',\n  ')},\n} from './lib/schema-types';`
    );
  }

  writeFileSync(
    `${base}/index.ts`,
    `// THIS FILE IS AUTOGENERATED by tools/generateApiIndex.js — EDIT WITH CAUTION
//
// The generated \`gql/index.ts\` only re-exports the \`graphql()\` helper, so the
// operation documents and types come from \`gql/graphql\` directly. Schema types
// the operations file does not emit are re-exported by name below.
export * from './lib/gql/graphql';

${blocks.join('\n\n')}

export { default as possibleTypes } from './lib/possible-types';
${tail}
`
  );
  console.log(
    `wrote ${base}/index.ts (${types.length} types, ${enums.length} enums)`
  );
}
