const fs = require('fs')
const path = require('path')

/**
 * Regenerates the barrel file re-exporting all near-operation-file codegen
 * outputs (schemas/*.generated.ts), so `@wepublish/editor/api` keeps exposing
 * every operation without manual upkeep. Runs as part of `npm run generate-api`.
 */
const schemaDirs = ['libs/editor/api/src/lib/schemas']

for (const dir of schemaDirs) {
  const files = fs
    .readdirSync(dir)
    .filter(f => f.endsWith('.generated.ts'))
    .sort()

  const lines = [
    '// THIS FILE IS AUTOGENERATED — re-exports all generated operation files',
    ...files.map(f => `export * from './${f.replace(/\.ts$/, '')}';`),
    '',
  ]

  fs.writeFileSync(path.join(dir, 'index.ts'), lines.join('\n'))
  console.log(`wrote ${dir}/index.ts (${files.length} files)`)
}
