export const redirectMap = new Map([
  ['bestellen.10.0.html', 'newsletter'],
  ['Gelesen-gedacht.21.0.html', 'a/tag/Gelesen%20&%20gedacht'],
  ['Gast-Kommentar.15.0.html', 'a/tag/Politik'],
  ['Kommentar.17.0.html', 'a/tag/Politik'],
  ['Faits-divers.24.0.html', 'a/tag/Kultur%20&%20Gesellschaft'],
  ['Kreative.25.0.html', 'a/tag/Kultur%20&%20Gesellschaft'],
  ['Konsum.12.0.html', 'a/tag/Kultur%20&%20Gesellschaft'],
  ['OEkologie.13.0.html', 'a/tag/Kultur%20&%20Gesellschaft'],
  ['Gesellschaft.14.0.html', 'a/tag/Kultur%20&%20Gesellschaft'],
  ['Kultur.16.0.html', 'a/tag/Kultur%20&%20Gesellschaft'],
  ['Wirtschaft.19.0.html', 'a/tag/Wirtschaft'],
  ['Politik.18.0.html', 'a/tag/Politik'],
  ['News.20.0.html', 'a/tag/news'],
  [
    'News.117+M5dafe69e252.0.html',
    'a/komitee-lanciert-abstimmungskampagne-gegen-birsigpark-in-binningen',
  ],
  [
    'News.117+M5c0a4597561.0.html',
    'a/erhebung-jedes-dritte-kind-in-baselland-spricht-ungenuegend-deutsch',
  ],
  [
    'Melanie-Nussbaumer-Mit-links.1779+M5346980ddb8.0.html',
    'a/kolumne-mit-links-von-melanie-nussbaumer-adolescence-wir-muessen-hinschauen',
  ],
  [
    'News.109+M558080683c2.0.html',
    'a/barockoper-dido-and-aeneas-von-henry-purcell-am-theater-basel',
  ],
  [
    'News.117+M5a49bacda02.0.html',
    'a/mann-in-birsfelden-von-auto-erfasst-schwer-verletzt',
  ],
  [
    'News.117+M555fc1e20d2.0.html',
    'a/harley-lenker-stirbt-bei-kollision-mit-einem-peugeot-in-kilchberg-bl',
  ],
  [
    'News.109+M509f746e181.0.html',
    'a/lisa-mathys-im-onlinereports-monatsgespraech-die-sp-ist-nicht-der-gegenpol-zur-svp',
  ],
  [
    'News.117+M55766a3819a.0.html',
    'a/frau-prallt-in-rheinfelden-mit-auto-gegen-kirchenmauer-und-stirbt',
  ],
  [
    'Carmela-Monsanto-Achtung-Satire.1383+M5df8cf6cc1b.0.html',
    'a/kolumne-achtung-satire-von-carmela-monsanto-sekt-kaviar-und-inseln',
  ],
  [
    'News.117+M50e1498e54c.0.html',
    'a/der-baselbieter-uni-standort-dreispitz-ist-vorerst-vom-tisch',
  ],
  [
    'News.117+M5539b068cb3.0.html',
    'a/julia-baumgartner-soll-praesidentin-der-basler-sp-werden',
  ],
  [
    'News.117+M5fcd005733b.0.html',
    'a/toetungsdelikt-im-jahr-2000-baselbieter-staatsanwaltschaft-erhebt-anklage',
  ],
  [
    'News.109+M51e8796862a.0.html',
    'a/buchbesprechung-musikleben-im-baselbiet-von-sigfried-schibli',
  ],
  [
    'News.99+M57cb535dc3e.0.html',
    'a/buechercheck-daniel-izquierdo-haenni-gefaehrliches-wasser',
  ],
  [
    'News.99+M58f291cacc3.0.html',
    'a/basel-stadt-stephanie-eymann-und-ex-kapo-chef-martin-roth-einigen-sich',
  ],
  [
    'Max-Kaufmann-Aus-meiner-Bubble.1348+M5f27be250fe.0.html',
    'a/kolumne-aus-meiner-bubble-von-max-kaufmann-jogging-der-lauf-ins-buenzlitum',
  ],
  [
    'News.99+M5c19808a871.0.html',
    'a/grossrat-oliver-bolliger-ist-neuer-praesident-von-basta-in-basel-stadt',
  ],
  [
    'News.99+M5a8f6621ea0.0.html',
    'a/auch-die-rechnung-2024-des-kantons-basel-stadt-schliesst-ueber-budget-ab',
  ],
  [
    'News.99+M598d831d15c.0.html',
    'a/unfall-mit-bus-an-der-hochbergerstrasse-in-basel-vier-verletzte',
  ],
  [
    'News.109+M5dd475a3b47.0.html',
    'a/altlasten-ist-das-basler-klybeck-mit-chemiemuell-aufgeschuettet',
  ],
  [
    'News.109+M53fbdb8d59f.0.html',
    'a/basel-riesenprojekt-laesst-alten-strassenbaeumen-an-der-missionsstrasse-keine-chance',
  ],
  [
    'News.99+M5287388f414.0.html',
    'a/kanton-baselland-mit-157-millionen-gewinn-statt-defizit',
  ],
  [
    'News.99+M529ade74402.0.html',
    'a/ksbl-reduziert-defizit-um-18-millionen-franken',
  ],
  [
    'News.99+M58efbc94da2.0.html',
    'a/ceo-florian-faber-verlaesst-mch-group-trotz-gewinn',
  ],
  [
    'News.99+M5e6580e674c.0.html',
    'a/asiatische-hornisse-in-beiden-basel-57-nester-entfernt',
  ],
  [
    'News.109+M5237ff81e52.0.html',
    'a/der-spartuechtige-verleger-peter-wanner-rettet-den-schwarzbueb',
  ],
  [
    'Andrea-Strahm-Alles-mit-scharf.986+M526d231d639.0.html',
    'a/kolumne-alles-mit-scharf-von-andrea-strahm-moskau-einfach',
  ],
  [
    'News.109+M5099222f5d8.0.html',
    'a/stephan-breitenmoser-es-ist-kein-zufall-dass-der-esc-in-basel-stattfindet',
  ],
  [
    'News.109+M5899fa9d409.0.html',
    'a/wie-gehen-das-wallis-und-basel-stadt-mit-giftmuell-um-ein-vergleich',
  ],
  [
    'News.99+M502ce058d23.0.html',
    'a/basler-standortpaket-sp-sagt-ja-und-veraergert-juso',
  ],
  [
    'News.109+M51e93f9596f.0.html',
    'a/pascal-ryf-es-kommt-bewegung-ins-rennen-um-maya-grafs-nachfolge-im-staenderat',
  ],
  [
    'News.99+M56c9c0c0aa1.0.html',
    'a/naturpark-baselbiet-die-sache-zieht-sich-hin',
  ],
  [
    'News.109+M54c0b53d88c.0.html',
    'a/bundeshausreports-graf-fuerchtet-handysucht-imark-will-auf-dem-pannenstreifen-fahren',
  ],
  [
    'News.99+M56fddb7c3dc.0.html',
    'a/grosser-rat-basel-stadt-jo-vergeat-wird-fraktionspraesidentin-der-gruenen',
  ],
  [
    'News.109+M589bde3e380.0.html',
    'a/altlasten-im-klybeck-investoren-reagieren-auf-verbreitete-sorgen',
  ],
  [
    'News.109+M5a6d3dc622a.0.html',
    'a/uni-finanzierung-gruenliberale-katja-christ-will-traegerkantone-entlasten',
  ],
  [
    'Das-aktuelle-Bild.130+M56999676c11.0.html',
    'a/das-wort-zum-bild-der-efeubaum',
  ],
  [
    'Marc-Schinzel-Schinzel-Pommes.1368+M5d81088d204.0.html',
    'a/kolumne-von-marc-schinzel-unterwegs-im-nahen-osten',
  ],
  [
    'News.109+M5ab30d03739.0.html',
    'a/fasnacht-baselland-leere-beizen-in-gelterkinden-und-sissach',
  ],
  [
    'News.99+M537c683b41d.0.html',
    'a/astrophysiker-maurizio-falanga-56-jaehrig-gestorben',
  ],
  [
    'Kultur.111+M5468ba67451.0.html',
    'a/die-oper-das-schlaue-fuechslein-am-theater-basel',
  ],
  [
    'News.99+M5e54be9cdb5.0.html',
    'a/1-5-millionen-menschen-haben-basler-museen-besucht',
  ],
  ['News.99+M5d34f5ecf8d.0.html', 'a/basel-stadt-will-88-meter-hochhaus-bauen'],
  [
    'Das-aktuelle-Bild.130+M5c7d4787bc4.0.html',
    'a/das-wort-zum-bild-wo-die-zitronen-bluehn',
  ],
  [
    'Gesellschaft.112+M55f08ea25cc.0.html',
    'a/kevin-schlaepfer-die-sprache-in-der-garderobe-ist-immer-noch-derb',
  ],
  [
    'Das-aktuelle-Bild.130+M5667e56e40e.0.html',
    'a/das-wort-zum-bild-jo-biden-schaffts',
  ],
  [
    'Gesellschaft.112+M56d6639c28f.0.html',
    'a/ukw-ausstieg-die-srg-zahlt-die-zeche-fuer-den-entscheid-des-bundesrats',
  ],
  [
    'Das-aktuelle-Bild.130+M55c49062200.0.html',
    'a/das-wort-zum-bild-fuenf-sterne-insektenhotel',
  ],
  [
    'Politik.110+M526ac19d1be.0.html',
    'a/weil-er-gemeindepraesident-ist-bekommt-ferdinand-pulver-keine-iv-mehr',
  ],
  [
    'Gesellschaft.112+M5c30b40ffe3.0.html',
    'a/letizia-elia-wir-profitieren-stark-vom-esc-auch-ohne-uebertriebene-preise',
  ],
  [
    'Das-aktuelle-Bild.130+M54c0450be29.0.html',
    'a/das-wort-zum-bild-velos-vs-autos-wer-gewinnt',
  ],
  [
    'Politik.110+M5ba7a69aa54.0.html',
    'a/maya-graf-es-koennte-eine-chance-sein-die-allianz-im-westen-zu-erweitern',
  ],
  [
    'Gesellschaft.112+M53da67d9687.0.html',
    'a/minu-im-onlinereports-monatsgespraech-heute-ist-weihnachten-laut',
  ],
  [
    'Das-aktuelle-Bild.130+M5d8a6b5fe53.0.html',
    'a/das-wort-zum-bild-santiglaus-ohne-sack',
  ],
  [
    'Wirtschaft.98+M58255c5ca83.0.html',
    'a/stephan-fricker-engelberger-macht-raumschutz-fuer-sein-unispital-punkt',
  ],
  [
    'Das-aktuelle-Bild.130+M5125201622a.0.html',
    'a/das-wort-zum-bild-100-jahre-statt-100-punkte',
  ],
]);
