name: Deploy pull request

on:
  pull_request:

jobs:
  publish-docker-image:
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      tags: |
        ghcr.io/wepublish/wepublish:${{ github.sha }}
    secrets: inherit

  deploy-to-k8s:
    uses: ./.github/workflows/deploy-to-k8s.yml
    needs: publish-docker-image
    with:
      image: ghcr.io/wepublish/wepublish:${{ github.sha }}
    secrets: inherit
