name: Deploy frontend on comment

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  check-deploy-label:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.extract_project_name.outputs.project_name }}
    steps:
      - name: Check for Deploy_ Label and Extract Project Name
        id: extract_project_name
        run: |
          project_name=""
          for label in $(echo "${{ toJSON(github.event.pull_request.labels) }}" | jq -r '.[].name'); do
            if [[ "$label" == deploy_* ]]; then
              project_name="${label#deploy_}"  # Remove "deploy_" prefix to get project name
              break
            fi
          done
          echo "Found project: $project_name"
          echo "::set-output name=project_name::$project_name"

  helm_deployment_website:
    name: Helm Deployment Website
    needs: [check-deploy-label]
    if: ${{ needs.check-deploy-label.result == 'success' }}
    uses: ./.github/workflows/on-demand-deploy-helm-website.yml
    with:
      website_project: ${{needs.deploy-frontend-on-comment.outputs.project_name}}
      api_url: https://api-${{ github.event.pull_request.number }}.reviews.wepublish.dev
    secrets: inherit
