name: Deploy frontend on comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy-frontend-on-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/deploy::') }}
    outputs:
      project_name: ${{ steps.set-extract_project_name.outputs.project_name }}
    env:
      COMMENT_BODY: ${{ github.event.comment.body }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Project Name from Comment
        id: extract_project_name
        run: |
          for i in $(echo $COMMENT_BODY); do PROJECT_NAME=$(echo $i | grep "/deploy::" |cut -d':' -f 3 ); if [[ ! -z $PROJECT_NAME ]]; then break; fi  ; done
          echo $PROJECT_NAME
          echo "::set-output name=project_name::${PROJECT_NAME}"

  helm_deployment_website:
    name: Helm Deployment Website
    needs: [deploy-frontend-on-comment]
    if: ${{ needs.deploy-frontend-on-comment.result == 'success' }}
    uses: ./.github/workflows/on-demand-deploy-helm-website.yml
    with:
      website_project: ${{needs.deploy-frontend-on-comment.outputs.project_name}}
      api_url: https://api-${{ github.event.pull_request.number }}.reviews.wepublish.dev
    secrets: inherit
