name: Publish docker base image

on:
  workflow_call:

jobs:
  build-and-push-base-image:
    name: Build and push base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Calculate hash of package-lock.json
        id: hash
        run: |
          if [ -f package-lock.json ]; then
            echo "HASH=$(cat package-lock.json Dockerfile | sha256sum | awk '{print $1}')" >> $GITHUB_ENV
          else
            echo "package-lock.json not found, exiting."
            exit 1
          fi

      - name: Set hash tag
        run: echo "HASHED_TAG=ghcr.io/wepublish/base-image:${{ env.HASH }}" >> $GITHUB_ENV

      - name: Check if image exists
        id: check-image
        run: |
          if docker manifest inspect ${{ env.HASHED_TAG }} > /dev/null 2>&1; then
            echo "Image with hash ${{ env.HASH }} already exists."
            echo "::set-output name=image-exists::true"
          else
            echo "Image with hash ${{ env.HASH }} does not exist."
            echo "::set-output name=image-exists::false"
          fi

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        if: steps.check-image.outputs.image-exists == 'false'
        with:
          target: base-image
          push: true
          tags: |
            ${{ env.HASHED_TAG }}