name: Publish docker base image

on:
  workflow_call:
    inputs:
      base_image_tags:
        required: true
        type: string

jobs:
  build-and-push-base-image:
    name: Build and push base Image
    runs-on: ubuntu-latest
    if: inputs.storybook_tags != ''
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          target: base-image
          push: true
          tags: |
            ${{ inputs.base_image_tags }}