name: Publish docker base image

on:
  workflow_call:
    inputs:
      base_image_tags:
        required: true
        type: string

jobs:
  build-and-push-base-image:
    name: Build and push base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calculate hash of package-lock.json
        id: hash
        run: |
          if [ -f package-lock.json ]; then
            echo "HASH=$(sha256sum package-lock.json | awk '{print $1}')" >> $GITHUB_ENV
          else
            echo "package-lock.json not found, exiting."
            exit 1
          fi

      - name: Set hash tag
        run: echo "HASHED_TAG=ghcr.io/${{ github.actor }}/base:${{ env.HASH }}" >> $GITHUB_ENV

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image exists
        id: check-image
        run: |
          IMAGE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" https://ghcr.io/v2/${{ github.actor }}/base/manifests/${{ env.HASH }})
          if [ "$IMAGE_EXISTS" -eq 200 ]; then
            echo "Image with hash ${{ env.HASH }} already exists."
            echo "::set-output name=image-exists::true"
          else
            echo "Image with hash ${{ env.HASH }} does not exist."
            echo "::set-output name=image-exists::false"

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        if: steps.check-image.outputs.image-exists == 'false'
        with:
          target: base-image
          push: true
          tags: |
            ${{ env.HASHED_TAG }}