name: Publish release artifacts

on:
  push:
    tags:
      - v*

jobs:

  release_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/*/}"

  alpha_release_docker:
    if: |
      contains(github.ref, 'tags/') && contains(github.ref, 'alpha')
    needs: release_version
    uses: ./.github/workflows/on-demand-publish-docker-image.yml
    with:
      editor_tags: |
        ghcr.io/wepublish/editor:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/editor:next
        wepublishch/editor:${{ needs.release_version.outputs.version }}
      api_tags: |
        ghcr.io/wepublish/api:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/api:next
        wepublishch/api:${{ needs.release_version.outputs.version }}
      migration_tags: |
        ghcr.io/wepublish/migration:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/migration:next
        wepublishch/migration:${{ needs.release_version.outputs.version }}
      storybook_tags: |
        ghcr.io/wepublish/storybook:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/storybook:next
        wepublishch/storybook:${{ needs.release_version.outputs.version }}
      website_tags: |
        ghcr.io/wepublish/website:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/website:next
        wepublishch/website:${{ needs.release_version.outputs.version }}
      media_tags: |
        ghcr.io/wepublish/media:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/media:next
        wepublishch/media:${{ needs.release_version.outputs.version }}
    secrets: inherit

  release_docker:
    if: |
      contains(github.ref, 'tags/') && !contains(github.ref, 'alpha')
    needs: release_version
    uses: ./.github/workflows/on-demand-publish-docker-image.yml
    with:
      editor_tags: |
        ghcr.io/wepublish/editor:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/editor:latest
        wepublishch/editor:${{ needs.release_version.outputs.version }}
        wepublishch/editor:latest
      api_tags: |
        ghcr.io/wepublish/api:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/api:latest
        wepublishch/api:${{ needs.release_version.outputs.version }}
        wepublishch/api:latest
      migration_tags: |
        ghcr.io/wepublish/migration:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/migration:latest
        wepublishch/migration:${{ needs.release_version.outputs.version }}
        wepublishch/migration:latest
      storybook_tags: |
        ghcr.io/wepublish/storybook:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/storybook:latest
        wepublishch/storybook:${{ needs.release_version.outputs.version }}
        wepublishch/storybook:latest
      website_tags: |
        ghcr.io/wepublish/website:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/website:latest
        wepublishch/website:${{ needs.release_version.outputs.version }}
        wepublishch/website:latest
      media_tags: |
        ghcr.io/wepublish/media:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/media:latest
        wepublishch/media:${{ needs.release_version.outputs.version }}
        wepublishch/media:latest
    secrets: inherit
