name: Publish packages

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Use NodeJS 12"
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: yarn

      - name: "Setup yarn/npm"
        run: |
          yarn config set registry 'https://registry.npmjs.org'
          npm set '//registry.npmjs.org/:_authToken' '${{ secrets.NPM_AUTH_TOKEN }}'

      - name: "Yarn install"
        run: yarn install --pure-lockfile

      - name: "Build"
        run: yarn run build:production

      - if: "contains(github.ref, 'tags/') && contains(github.ref, 'alpha')"
        name: "Publish next npms"
        run: yarn run publish:next --yes

      - if: "contains(github.ref, 'tags/') && !contains(github.ref, 'alpha')"
        name: "Publish latest npms"
        run: yarn run publish --yes

  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set RELEASE_DATE env
        run: echo "RELEASE_DATE=$(date +%s)" >> $GITHUB_ENV

      - if: "github.ref == 'refs/heads/master'"
        name: "Build and push on master"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:master-${{ env.RELEASE_DATE }}-${{ github.sha }}

      - if: "contains(github.ref, 'refs/pull/')"
        name: "Build and push on master"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:pr-

      - if: "contains(github.ref, 'tags/') && contains(github.ref, 'alpha')"
        name: "Build and push on alpha release"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:${{ env.RELEASE_VERSION }}

      - if: "contains(github.ref, 'tags/') && !contains(github.ref, 'alpha')"
        name: "Build and push on non-alpha tag"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:${{ env.RELEASE_VERSION }}
            ghcr.io/wepublish/wepublish:latest
