name: Publish

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish-docker-images:
    uses: ./.github/workflows/publish-docker-images.yml
    with:
      image: ghcr.io/wepublish/wepublish:${{ github.sha }}
    secrets: inherit

  deploy-to-k8s:
    uses: ./.github/workflows/deploy-to-k8s.yml
    needs: publish-docker-images
    with:
      image: ${{ needs.publish-docker-images.outputs.image }}
    secrets: inherit
