name: Publish on tags

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Use NodeJS 12"
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: yarn

      - name: "Setup yarn/npm"
        run: |
          yarn config set registry 'https://registry.npmjs.org'
          npm set '//registry.npmjs.org/:_authToken' '${{ secrets.NPM_AUTH_TOKEN }}'

      - name: "Yarn install"
        run: yarn install --pure-lockfile

      - name: "Build"
        run: yarn run build:production

      - if: "contains(github.ref, 'alpha')"
        name: "Publish next npms"
        run: yarn run publish:next --yes

      - if: "!contains(github.ref, 'alpha')"
        name: "Publish latest npms"
        run: yarn run publish --yes

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - if: "contains(github.ref, 'alpha')"
        name: "Build and push alpha"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:${{ env.RELEASE_VERSION }}

      - if: "!contains(github.ref, 'alpha')"
        name: "Build and push latest"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:${{ env.RELEASE_VERSION }}
            ghcr.io/wepublish/wepublish:latest
